### PR TITLE
Feature/associated inputs

### LINKED ISSUE #5078: [UX] Unable to have two SubmitAction Buttons *and* validation
# Platform

- [x] .NET WPF (#5137)
- [x] Android (#5152)
- [x] iOS (#5148)
- [X] JavaScript (#5136)
- [x] UWP (#5141)
- [x] Shared Model (#5139)
- [x] Schema (#5140)
- [ ] Merge feature branch to main (#5078)

# Author or host

Author

If you're an author, who are you sending cards to?

Own host.

# Version of SDK

2.5.0

# Details

With 1.3, input validation and `required` was added to some of the input controls, which is great. However, I'm running into a problem whereby I need multiple SubmitAction buttons on the page for different purposes, but none of them will work unless all the validation has been met.

User scenario: I create a form card with several `Input.Text` fields, at the bottom, I have a SubmitAction button with a label and id of "Submit", but I also want to offer the user a way to cancel this screen and go back to the previous screen, so I would add another SubmitAction button with a label and id of "Cancel", but the user can't do anything with the cancel button because the form validation may not be meeting the required validation criteria. 

This would apply to any additional SubmitAction buttons in the card (maybe I have a logo image with an attached SubmitAction that takes the user back to the "home" card, for example), none of these will work unless the user actually fills in all the forms.

### PR DESCRIPTION
**Pull request by RebeccaAnne**
## Related Issue
Fixes #5078

## Description
Merges feature branch containing all platforms implementations of asssociatedInputs none to main

## Sample Card
Sample card added as samples\v1.3\Elements\Action.Submit.AssociatedInputs.json

## How Verified
See individual PRs for per platform verification performed

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/5155)

### CODE REVIEW

**Comment by golddove** [comment]
@RebeccaAnne @paulcam206 what was the resolution about the XML doc files? Do we want to commit and start tracking them?

**Comment by RebeccaAnne** [comment]
> @RebeccaAnne @paulcam206 what was the resolution about the XML doc files? Do we want to commit and start tracking them?

I can delete them if we don't want them. But if we don't want them we should also add them to .gitignore because right now everytime I build .NET they show up and I have to delete them. Or, alternatively, if they're supposed to get deleted by the build process we should figure out why they don't (at least locally for me).

**Comment by RebeccaAnne** [comment]
I went ahead and deleted them and logged #5157 to figure out what we want to happen to these.

**Review by golddove — APPROVED** [review]

**Review by paulcam206 — APPROVED** [review]

**Comment by paulcam206** [comment]
you can ignore the failing `Generate Specs` check -- it's failing to push changes to the branch due to branch protection rules

**Pull request merged**
