### PR TITLE
User/shalinijoshi19/1.2.4

### PR DESCRIPTION
**Pull request by shalinijoshi19**
## Description
Cherry-pick changes for v1.2.4

## How Verified
TBD

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/3561)

### CODE REVIEW

**Comment by shalinijoshi19** [comment]
@paulcam206, this is missing your UWP cpp/winrt changes (can you mark your PR with the 1.2.4 label if we dont have a github issue tracking this?) , @nesalang this is also missing your threading changes from yesterday; could you CP them over and push back onto this branch? Also @paulcam206 FYI that i'd run into some merge conflicts CP'ing your changes over and needed to pull in the entire XAMLBuilder refactor.. Can you double check things are looking ok there as you CP the remaining change over? Thanks!

**Comment by paulcam206** [comment]
> @paulcam206, this is missing your UWP cpp/winrt changes (can you mark your PR with the 1.2.4 label if we dont have a github issue tracking this?) , 

I already had the 1.2.4 label on the PR... I just filed #3562 (with the label) to track in case we need an issue to reference.

> Also @paulcam206 FYI that i'd run into some merge conflicts CP'ing your changes over and needed to pull in the entire XAMLBuilder refactor.. Can you double check things are looking ok there as you CP the remaining change over? Thanks!

Yep -- will do once I get my change in :)

**Comment by almedina-ms** [comment]
I just tested .NET and it works correctly

**Comment by nesalang** [comment]
.Net merging seems to be correct for concurrency & outdated warning messages issues.
ios is verified.

**Comment by paulcam206** [comment]
superceded by #3565

**Pull request closed without merging**
