### PR TITLE
Reactnative/release 2.1

### PR DESCRIPTION
**Pull request by vivekvijayakrishnan**
Please find the below task/issues completed:

**Release 2.1**

- Upgraded React-Native version.
- Refactored `Image` component.
- Added requires/fallback support.
- Added theme config support [wiki](https://github.com/microsoft/AdaptiveCards/wiki/React-Native-Theme-Config-Support)
- Fixed keyboard issues
- Fixed Issues in `BackgroundImage`  component.
- Handled container style issues.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/4056)

### CODE REVIEW

**Comment by paulcam206** [comment]
your PR builds are failing because you have a space at the end of the filename `.eslint.js`, so the build agents are failing to complete checkout:

```
git checkout --progress --force refs/remotes/pull/4056/merge
error: invalid path 'source/community/reactnative/.eslintrc.js '
```

**Comment by paulcam206** [comment]
(just a heads up) 👍

**Comment by vivekvijayakrishnan** [comment]
> the PR builds are failing here because you have a space at the end of the filename `.eslint.js`, so the build agents are failing to complete git checkout:
> 
> ```
> git checkout --progress --force refs/remotes/pull/4056/merge
> error: invalid path 'source/community/reactnative/.eslintrc.js '
> ```

Thanks for the support :) @paulcam206

**Pull request merged**
