### PR TITLE
[Android] Updates for version1.1.1

### PR DESCRIPTION
**Pull request by almedina-ms**
Includes this two commits: 
* https://github.com/microsoft/AdaptiveCards/pull/2258
* https://github.com/microsoft/AdaptiveCards/pull/2330

This had already been merged:
* https://github.com/microsoft/AdaptiveCards/pull/2402

### CODE REVIEW

**Comment by paulcam206** [comment]
Looks like we need to [bring in the gradle version updates](https://stackoverflow.com/questions/52193274/no-toolchains-found-in-the-ndk-toolchains-folder-for-abi-with-prefix-mips64el-l) here. The Android build is failing:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':adaptivecards'.
> No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android
```

**Comment by almedina-ms** [comment]
I cherry-picked the build fix to this branch too

---
In reply to: [490244962](https://github.com/microsoft/AdaptiveCards/pull/2860#issuecomment-490244962) [](ancestors = 490244962)

**Comment by paulcam206** [comment]
Manually ran the failing `AC-Android-CI` job since it seems to not be triggered for some reason (possibly because this is a PR into a release branch). Job succeeded, as did our other Android job, so I'm going to commit this. :)

**Pull request merged**
