### PR TITLE
Fix ActionSet description

### PR DESCRIPTION
**Pull request by v-kydela**
## Description
Just fixing a typo

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/3423)

### CODE REVIEW

**Comment by shalinijoshi19** [comment]
@v-kydela, do you still have the patch-1 branch up? @paulcam206 ideas on the error in the Generate Specs job above ? https://microsoft.visualstudio.com/AdaptiveCards/_build/results?buildId=18531560&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=70b92200-87db-50c8-35f9-975ba5f9e5b7&l=12

**Comment by v-kydela** [comment]
@shalinijoshi19 - I do still have the branch up

**Comment by v-kydela** [comment]
@dclaux 
@shalinijoshi19 
@matthidinger 

Sorry for the trouble. I'm not sure why "Generate Specs" isn't passing, but I'm guessing it's comparing the schema's descriptions to some other file somewhere and noticing they don't match. I can't see the details of the error, but I presume you can. Can you help figure out why this typo fix can't be merged?

**Comment by dclaux** [comment]
Unfortunately I have no idea what might be going on. Adding @paulcam206.

**Comment by v-kydela** [comment]
@paulcam206 - Can you help with this quick fix?

**Comment by paulcam206** [comment]
Here's why the `Generate Specs` job is failing:
* its purpose is to build spec markdown files out of the various descriptive json files (like `ActionSet.json` changed here)
* once the markdown files are built, it commits the changes and pushes them to the originating branch
* since this PR is coming from a fork, the checkout phase is failing

This would be tricky to fix. Indeed, I'm not entirely sure that this can be fixed in a generalized way. _However_, I think we can safely take this change even with the failing job -- the next PR to come through against spec stuff will automatically generate all of the changes.

**Comment by v-kydela** [comment]
@dclaux - Would you like to merge it now?

**Comment by v-kydela** [comment]
@paulcam206 - Can you merge this?

**Pull request merged**
