### PR TITLE
Staging remaining 1.2.3 changes mostly around JS platform

### PR DESCRIPTION
**Pull request by shalinijoshi19**
## Description
1. .NET: Updating nuget package version ahead of 1.2.3 release
2. JS: Pulling in snapshots of everything under nodejs folder from master to bulk absorb post-1.2.0 JS changes
- adaptivecards
- adaptivecards-designer
- adaptivecards-visualizer
- adaptivecards-designer-app
- adaptivecards-controls
- adaptivecards-site
- ac-typed-schema
- schema-generator

## How Verified
In progress using local builds at the moment. 
Pending: Bug bash validation next week.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/3473)

### CODE REVIEW

**Comment by shalinijoshi19** [comment]
@Paulcam206, can you help wtih the CI failures a bit? Esp .NET PR failing with 

 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(821,5): Error : Certificate does not match supplied signing thumbprint: AAA0D57E7E50E44C031C2996A07C85E5849B2EC0"

**Comment by paulcam206** [comment]
> @paulcam206, can you help wtih the CI failures a bit? Esp .NET PR failing with
> 
> "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(821,5): Error : Certificate does not match supplied signing thumbprint: AAA0D57E7E50E44C031C2996A07C85E5849B2EC0"

Looks like this is largely due to using the new machine pool against the old codebase. Let me take a look :)

**Comment by shalinijoshi19** [comment]
At this poitn I am going to go ahead and merge this in to release/1.2 ; @PaulCam206 let's tackle any remaining CI failures in the release branch builds please.. Thanks

**Pull request merged**
