### PR TITLE
Use compact transport controls

### PR DESCRIPTION
**Pull request by achipa**
https://github.com/microsoft/AdaptiveCards/issues/2528

Uses compact transport controls for UWP rendering, which is better suited for small, card-oriented rendering sizes.

Don't show zoom button in UWP rendering, as it makes no sense in Adaptive Cards - there is no way to force an aspect ratio, so a zoom button is effectively a no-op within a card, just using up scant screen real-estate.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/2987)

### CODE REVIEW

**Comment by paulcam206** [comment]
@shalinijoshi19 / @RebeccaAnne - do we want this for 1.2?

**Comment by andrewleader** [comment]
If dev team feels comfortable with this for 1.2, I think that's the right decision and a really easy win to help our partner, HP, who needs this!

**Comment by shalinijoshi19** [comment]
> @shalinijoshi19 Shalini Joshi (WINDOWS) FTE / @RebeccaAnne Rebecca Muraira FTE - do we want this for 1.2?

Thanks @paulcam206 ; Indeed sounds like an improvement here. If there are no regressions etc and since it's already been reviewed i dont mind this being part of the 1.2 payload (though it will need to be manually merged in @paulcam206 / @RebeccaAnne  since we've now forked the 1.2 branch off of master)

**Pull request merged**
