### PR TITLE
[JS] Build docs automatically when running release

### PR DESCRIPTION
**Pull request by paulcam206**
## Description
Prior to this change, docs would only get generated if you manually ran `npm run docs`. You can still do manual generation, but I reworked the `release` script to:
* Add docs generation
* Parallelize some of our tasks

The first commit (c9c0f77) has the script changes, and the second (546c360) contains the generated doc changes. Here's a [link](https://github.com/microsoft/AdaptiveCards/tree/paulcam/automatic-nodejs-docs/source/nodejs/adaptivecards/docs) to just the docs (in readable form).

## How Verified
* local clean build
* spot check on some of the docs

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/4018)

### CODE REVIEW

**Comment by shalinijoshi19** [comment]
@paulcam206 what's the story for getting these published to the microsoftdocs repo (and subsequently getting rid of teh version here) ?

**Comment by paulcam206** [comment]
> @paulcam206 what's the story for getting these published to the microsoftdocs repo (and subsequently getting rid of teh version here) ?

We don't currently have a story. We need to figure out a docs versioning story and finish getting our docs fleshed out. Eventually the story will likely involve copying our docs over to the other repo in some subdir. For now I think it's probably sufficient to put links in our existing docs to point to our "in progress" docs.

**Pull request merged**
