### PR TITLE
Fix typo in ActionSet description

### PR DESCRIPTION
**Pull request by peterdemin**
## Description
`ActionSet` documentation states that it is an array of images, which is obviously not true.
I replaced `Image` with `Action` across multiple files with the same text.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/3895)

### CODE REVIEW

**Comment by peterdemin** [comment]
Ping

**Comment by shalinijoshi19** [comment]
@Paulcam206 ideas on the failing spec build?

**Comment by peterdemin** [comment]
Ping

**Comment by paulcam206** [comment]
looks like this is fixed!

**Pull request closed without merging**
