### PR TITLE
Fix typo in image alt text

### PR DESCRIPTION
**Pull request by vintagesucks**
## Description
Fixes the typo `Screnshot` in an image alt text on https://adaptivecards.io/blog/2019/Community-Call-October/, which should be `Screenshot` instead.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/4868)

### CODE REVIEW

**Review by golddove — APPROVED** [review]

**Comment by vintagesucks** [comment]
> once the JS build succeeds, please go to the [test site](https://adaptivecardsci.z5.web.core.windows.net/pr/4868) to test out your website/designer changes.

👍

**Comment by shalinijoshi19** [comment]
@golddove you may need to shepherd this in and merge it after diagnosing the Android-CI build issues here.

**Review by shalinijoshi19 — APPROVED** [review]

**Comment by golddove** [comment]
Good catch, and thanks for the fix @vintagesucks. We were having some issues with our CI earlier, but this should be merged shortly.

**Pull request merged**
