### PR TITLE
supporting strings and objects for SubmitAction data

### PR DESCRIPTION
**Pull request by ignacionr**
Fixes: the C++ model supported SubmitAction data property roundtrip only if a string.
Likely to be related to https://github.com/Microsoft/AdaptiveCards/issues/945 or similar issues. The original code would parse an object but would only set a string.

### CODE REVIEW

**Comment by ignacionr** [comment]
Also notice a separate method for getting the property value as a Json::Value was created (so to not break existing code that may depend on the string-only interface).

**Comment by ignacionr** [comment]
Caught a bug with the card empty constructor leaving the style uninitialized (this was causing random exceptions). Removed unnecessary string copying on parameter passing.

Shy to remove some obvious misinterpretations of the 'const' keyword (like passing shared pointers as const copy on the pointer, and passing copies of enums as const) because I miss what the intent might have been (other than just lack of understanding of what const means). They're just bad coding but at least don't hurt performance or semantics.

**Comment by ignacionr** [comment]
Hey guys, this one is getting cold and will soon need manual merge. If you don't like it just let me know, we can discuss it. @RebeccaAnne I am shy to put things on your already big plate, but if you have a second to track this, do comment. Thanks!

**Comment by RebeccaAnne** [comment]
I approved this one back on May 18th, are you waiting on something else from me?

**Comment by ignacionr** [comment]
@RebeccaAnne do you think you can merge and close? I don't have write access...

**Comment by RebeccaAnne** [comment]
Ah, will do, didn't realize you needed us to do that. Thanks for the fixes!

**Pull request merged**
