### PR TITLE
[Samples][Accessibility] TextBlock wrap in Scenario cards

### PR DESCRIPTION
**Pull request by golddove**
## Related Issue
ADO 28383345

## Description
TextBlock should always be set to wrap (users who use very large font sizes should be able to see all text), unless there is a good reason not to.

## How Verified
Manual verification of scenarios on JS

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/4991)

### CODE REVIEW

**Comment by shalinijoshi19** [comment]
@golddove isnt this slated for 20.10? If so absent a backing issue should be going ahead and adding this to the ship milestone.

**Comment by golddove** [comment]
@shalinijoshi19 it's a sample update, so doesn't change the library. This doesn't need to go into the release branch

**Review by shalinijoshi19 — APPROVED** [review]

**Comment by shalinijoshi19** [comment]
Thanks. Does this sample get bubbled up through our website at all ? If so this should land in teh release branch since we'd be doing website deployments off of it. Also be good to update the release notes still wtih "misc sample updates" assuming the samples are showcased on our website. @RebeccaAnne

**Comment by golddove** [comment]
Sure, we can bring this one into release, to update the website.

**Pull request merged**
