### PR TITLE
Updating version to 2.0.0 for nuget release

### PR DESCRIPTION
**Pull request by shalinijoshi19**
Updating custom.props to 2.0.0

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/4525)

### CODE REVIEW

**Comment by paulcam206** [comment]
should this be going into `main` first?

**Comment by shalinijoshi19** [comment]
> should this be going into `main` first?

Yeah was in 2 minds about it (since it's release specific anyways needing to be updated in the release branch as part of release) but then it makes sense to update the essentially "placeholder" values in main also. I will just end up CP'ing this change over to main to avoid complicating this PR (_there were some additional files being pulled in with the rebase_)

**Pull request merged**
