### PR TITLE
[Xamarin] Implements missing functionality in renderers

### PR DESCRIPTION
**Pull request by Pepsi1x1**
This PR fixes some rendering issues in @almedina-ms xamarin forms branch and makes some progress towards #3255 

-Vertically stacked action sets now render correctly without overlapping at a single point
-Shadows on Frames have now been removed
-Sets the default wrap mode to wrap for text blocks
-Implements loading host configs on Xamarin iOS and Xamarin Android
-Applies padding, spacing, and margin for all elements as defined by the schema
-Hooks up binding contexts - this fixes action events
-Applies colours as defined by the schema or configs
-Renders radio buttons in choice sets
-Renders checkboxes in choice sets
-Implements tag content as an attached property
-Renders image sets corretly by using a flex layout
-Renders markdown in text blocks

- [ ] TextInputs - Multiline editor needs implementing
- [x] ChoiceSet - combobox (This should be rendered as an XF picker)
- [x] ToggleInputs - should move over to the CheckBox control added as part of this PR
- [x] RadialImages (Person type) - Write a Xamarin custom ~~renderer~~ effect
- [ ] On the Food Order card, the action buttons don’t render. 
- [ ] Some cards render with extra white space below. 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/4408)

### CODE REVIEW

**Comment by Pepsi1x1** [comment]
Ok, heres the current state of the renderers using the v1.0 samples from main

### FlightUpdate
FlightUpdate
### FoodOrder
FoodOrder

### ImageGallery
ImageGallery

### InputForm
InputForm

### Inputs
Inputs1
Inputs2
Inputs3

### Restaurant
Restaurant

### Solitaire
Solitaire

### SportingEvent
SportingEvent

### StockUpdate
StockUpdate

### WeatherCompact
WeatherCompact

### WeatherLarge
WeatherLarge

**Comment by Pepsi1x1** [comment]
Outstanding work to support v1

TextInputs - Multiline editor needs implementing
ChoiceSet - combobox (This should be rendered as an XF picker)
ToggleInputs - should move over to the CheckBox control added as part of this PR
RadialImages (Person type) - I don't see this as a blocker, we could write a Xamarin custom renderer ~~or wait for XF 4.8~~

Xamarin Forms 4.8 includes experimental Brush support which could significantly reduce the amount of pre-processors.

**Comment by matthidinger** [comment]
Hi @Pepsi1x1, this is looking really great and very much appreciated. Is your current plan to close those remaining items or use it as-is for now? Unfortunately we only have limited time available to support XF right now, but are there any high-impact ways we can support you with this work? If you get it to a stable 1.0 release we could setup Builds and NuGet publishing for example.

**Comment by Pepsi1x1** [comment]
Hi @matthidinger, thanks appreciate you taking the time to look over this.

I was waiting for 4.8 on the assumption that the brushes support would be a simple resolution for the radial image support, however OpacityMask isn't part of that change so it looks like a custom renderer is required.

I'm happy to work on the remaining issues in the knowledge that it has legs. 

Builds and publishing would be great once these are complete. Testing against a wide range of cards to prove the implementation is probably my barrier, also an understanding of the bar that performance was aiming for would be useful. This branch outputs the time taken to render cards but without context I'm unsure if this meets the required standards.

In light of this, it may make sense to convert this to a draft PR until those are complete?

**Comment by matthidinger** [comment]
@Pepsi1x1 making this a draft PR until you feel like it's ready for general consumption sounds reasonable to me. I will queue up a chat with the team internally about what we can provide for builds/CI and of course NuGet publishing, but I think I can make the case that if the community is willing to support this code that we can provide the infrastructure around it. Keep us posted how it's going!

**Comment by Pepsi1x1** [comment]
There are two outstanding visual issues to resolve before I’d consider this a stable build. 

On the Food Order card, the action buttons don’t render. 
Some cards render with extra white space below. 

I’ll need to investigate these using the Xamarin Inspector and see which elements in the visual hierarchy are the culprits.

**Comment by Pepsi1x1** [comment]
Just to keep you updated on this, I'm still actively working on this - the issue with the extra whitespace below some cards is proving a difficult one to isolate.

**Comment by jonmill** [comment]
Closing due to age - if this is still needed, please re-open

**Pull request closed without merging**
