### PR TITLE
Allow comma to be taken as a decimal point in the Number only input

### PR DESCRIPTION
**Pull request by AparnaHP**
Locales like Swedish (SV) use comma "," instead of "." as the decimal point

Very sorry I closed my previous PR due to the changes I had to do in 2.1 release.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/4153)

### CODE REVIEW

**Comment by shalinijoshi19** [comment]
> /azp run AdaptiveCards-SharedModel-CI, AdaptiveCards-.NET-PR, AdaptiveCards-NodeJS-Daily, AdaptiveCards-UWP-Daily-PRs, AdaptiveCards-Android-CI, AdaptiveCards-iOS-CI

Hey @paulcam206 what does it take to get the fabric bot account to help trigger CI builds again? Is that not possible because of the singlesign on requirements ?

**Comment by paulcam206** [comment]
> > /azp run AdaptiveCards-SharedModel-CI, AdaptiveCards-.NET-PR, AdaptiveCards-NodeJS-Daily, AdaptiveCards-UWP-Daily-PRs, AdaptiveCards-Android-CI, AdaptiveCards-iOS-CI
> 
> Hey @paulcam206 what does it take to get the fabric bot account to help trigger CI builds again? Is that not possible because of the singlesign on requirements ?

I think the problem here is that the comment was posted by msftbot, and not from a contributor to our project :)

**Comment by AparnaHP** [comment]
@BalajiR may I kindly know the status of the PR review?

**Comment by AparnaHP** [comment]
@dclaux , @BalajiR , @RebeccaAnne Can we please have this merged. Its important for users who uses "," as decimal point

**Comment by paulcam206** [comment]
@BalajiR - care to take a look at this or close?

**Comment by jonmill** [comment]
Closing due to age - if this is still needed, please re-open

**Pull request closed without merging**
