### PR TITLE
React native implementation of Adaptive card

### PR DESCRIPTION
**Pull request by Vasanth-S**
### High level notes on implementation
___
 We have built the,
* leaf components that can work as standalone based on the given props.
* container components
* AdaptiveCard that takes care of initial parsing & component creations
* HostConfig system

### CODE REVIEW

**Comment by matthidinger** [comment]
Hi @Vasanth-S, thanks for submitting this! A fellow Microsoft team recently published their version of a react-native renderer as well: https://github.com/Microsoft/react-native-adaptivecards

Can you help us understand the state of this renderer? Are you folks actively planning to maintain it and keep it in line with future adaptive cards releases? Ideally we can find some way to coordinate efforts and maintain a single react-naive implementation if at all possible

**Comment by Vasanth-S** [comment]
Hi @matthidinger, Appreciate the quick response. Please find below the report for the state of this renderer with due date marked for few minor items. 

# Adaptive Cards React-Native Renderer  Status
| Card Rendering Functionality  |  Completed / Planned Date |
| ------ | ------ | 
| **Card Rendering** 
| Render full schema |  ✓  | 
| Render actions bar |  ✓  | 
| Ignore unknown Elements | ✓  | 
| Host Config support | ✓  | 
| Native platform styling | ✓  | 
| Check for supported version | 12/7/2018 | 
| **Element Rendering** 
| Spacing and Separator |  ✓  | 
| TextBlock DATE/TIME formatting |  ✓  | 
| TextBlock Markdown support | ✓  | 
| Full Input support | ✓  | 
| **Actions**
| Action.OpenUrl support | ✓ | 
| Action.ShowCard support |  ✓  | 
| Action.Submit support |  ✓  | 
| selectAction support | ✓  | 
| **Parsing**
| Return validation failures | 12/7/2018  | 
| Parse unknown properties | 12/7/2018 | 
| **Extensbility**
| Override Element Renderer |  12/26/2018  | 
| Add new Element Renderer | 12/26/2018  | 
| Remove Element Renderer | 12/26/2018  | 
| Override/add/remove Action Renderer | 12/26/2018  | 
| **Events**
| Check for supported version | 12/7/2018 | 

We're committed to maintaining it and add new features (as per the roadmap).

We will also share our fork/status on the repo board. Happy to get on a call for a discussion, if needed.

**Comment by Vasanth-S** [comment]
Hi @matthidinger, I have updated above the current state of this renderer of the project. We have also added support for schema 1.1 and for video element rendering. We are working on adding more unit test cases and exploring on supporting schema 1.2 (once the spec finalised). We have a dedicated support team for maintenance and add new features. Do let's know your comments.

**Comment by matthidinger** [comment]
Hi @Vasanth-S, thanks for the update! Would you mind dropping me a mail at your convenience and we can setup a call? My email is first.last at microsoft

**Comment by dclaux** [comment]
@vasanth-s and @matthidinger I'd love to be on that call. Matt, can you forward me the invite when you get it?

**Comment by Vasanth-S** [comment]
Sure, @dclaux and @matthidinger. Matt, I have sent a mail regarding setting up a call. My email is vasanthDOTsATimagineaDOTcom .

**Comment by paulcam206** [comment]
Some checks didn't run, but as this is a new project, they're not important.

:shipit:

**Pull request merged**
