### PR TITLE
Fix certificate thumbprints

### LINKED ISSUE #3194: [UWP,X64, VS2019] solution fails to compile with a certificate mismatch error for the 2 store apps
# Platform

* UWP

# Version of SDK

latest master with VS2019

# Issue

Trying to compile the VS solution fails with the following errors in VS2019; Confirmed that this isnt an issue with VS2017

Severity	Code	Description	Project	File	Line	Suppression State
Error		Certificate does not match supplied signing thumbprint: 7DF59BF73D990455B63DFF7735D301D0BB319CD2	AdaptiveCardTestApp			
Error		Certificate does not match supplied signing thumbprint: BD1E51E915EF811D813E0C6C4143C44144367328	AdaptiveCardVisualizer

### PR DESCRIPTION
**Pull request by rudyhuyn**
Fixes #3194 

AdaptiveCardTestApp and AdaptiveCardVisualizer can't be compiled with the last update of Visual Studio 2019 (16.2) because the `PackageCertificateThumbprint` properties in .csproj files mismatch with certificates used.

More explanation here:
http://www.rudyhuyn.com/blog/2019/08/05/how-to-fix-certificate-does-not-match-supplied-signing-thumbprint/

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/3312)

### CODE REVIEW

**Comment by matthidinger** [comment]
You rock!

**Comment by rudyhuyn** [comment]
> You rock!

You're fast!

**Comment by shalinijoshi19** [comment]
> You rock!

Indeed! Thanks for fixing this @rudyhuyn !

**Comment by paulcam206** [comment]
this issue should be fixed - thanks for your PR!

**Pull request closed without merging**
