### PR TITLE
[.NET] Add markdown docs generation for AdaptiveCards library

### PR DESCRIPTION
**Pull request by paulcam206**
## Description

Adds support for generating markdown docs for the AdaptiveCards .NET library via the `vsxmd` nuget package. It couldn't be easier to use -- just document C# code with standard xmldoc comments and build. The updated docs should be placed in `source/dotnet/Library/AdaptiveCards/docs/`.

It's worth noting that originally I was looking at docfx as a solution, but it doesn't satisfy our needs. Despite [stating](https://dotnet.github.io/docfx/):
> DocFX can produce documentation from source code (including .NET, REST, JavaScript, Java, Python and TypeScript) as well as raw Markdown files.

You can't actually emit raw Markdown files. It's a poorly written statement because docfx can generate documentation that includes Markdown files *that you author* as part of its documentation. In other words, you can write your own Markdown files (e.g. samples or articles) and have them be included in the HTML generated by the tool. dotnet/docfx#684 tracks supporting Markdown as an **output format**, but it seems unlikely to get traction as the bug is four years old at this point.

There's a fair amount of public API surface exposed that lacks documentation in our library (VS emits warnings for public surfaces that lack docs), but addressing that will be in a future checkin.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/3952)

### CODE REVIEW

**Comment by paulcam206** [comment]
@jwoo-msft - this is pretty straightforward to add to your project in VS:
1. Right-click on your project and click `Manage Nuget Packages...`
2. Search for and install the `vsxmd` package
3. Right-click on your project and click `Properties`
4. In the `Build` tab's `Output` section, check the `XML documentation file` checkbox (don't worry about the path right now
5. Save the project
6. Right-click the project and choose `Edit Project File`
7. In the property group near the top (probably just under `DocumentationFile`, add:
```xml
<VsxmdAutoDeleteXml>True</VsxmdAutoDeleteXml>
```
8. Edit the `DocumentationFile` to be `$(MSBuildProjectDirectory)/docs/<whateveryourprojectnameis>.xml`
9. Save and close the project file and build the project

At this point you should have a new directory in your project directory named `docs` containing `<whateveryourprojectnameis>.md`. 👍

**Comment by jwoo-msft** [comment]
> @jwoo-msft - this is pretty straightforward to add to your project in VS:
> 
> 1. Right-click on your project and click `Manage Nuget Packages...`
> 2. Search for and install the `vsxmd` package
> 3. Right-click on your project and click `Properties`
> 4. In the `Build` tab's `Output` section, check the `XML documentation file` checkbox (don't worry about the path right now
> 5. Save the project
> 6. Right-click the project and choose `Edit Project File`
> 7. In the property group near the top (probably just under `DocumentationFile`, add:
> 
> ```
> <VsxmdAutoDeleteXml>True</VsxmdAutoDeleteXml>
> ```
> 
> 1. Edit the `DocumentationFile` to be `$(MSBuildProjectDirectory)/docs/<whateveryourprojectnameis>.xml`
> 2. Save and close the project file and build the project
> 
> At this point you should have a new directory in your project directory named `docs` containing `<whateveryourprojectnameis>.md`. 👍

Thanks!

**Pull request merged**
