### PR TITLE
Updated Bleed for iOS

### LINKED ISSUE #4745: [iOS][Rendering] Crash when "bleed" property used on outermost container
# Platform

* iOS

# Version of SDK

v1.2.11

# Details

When "bleed" property is used on the outermost container, the SDK crashes on [this line](https://github.com/microsoft/AdaptiveCards/blob/f9d6436cd489015a310fad5c62058391d0cadc4b/source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRContentStackView.mm#L399).

[bleed-card-payload.txt](https://github.com/microsoft/AdaptiveCards/files/5188285/bleed-card-payload.txt)
[bleed-crash-stacktrace.txt](https://github.com/microsoft/AdaptiveCards/files/5188286/bleed-crash-stacktrace.txt)
These are the card-payload and stack-trace.

### PR DESCRIPTION
**Pull request by jwoo-msft**
## Related Issue
Fixed #4745 

## Description
Setting the constraint with superview for bleed resulted in dependency on the superview. The fix limited the use of constraint to superview. Made explicit reference to the superview for code maintenance. 

## How Verified
1. Updated Bleed.Comprehensive.json to include a container with bleed in a showcard.
2. Ran regression tests, and verified the fix

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/4780)

### CODE REVIEW

**Comment by shalinijoshi19** [comment]
@jwoo-msft this might need to be ported to release/1.2 - let's confirm with the Teams mobile team tonight. Thanks!

**Review by shalinijoshi19 — APPROVED** [review]
Is this just an iOS issue? @RebeccaAnne should have a peek here too !

**Review by shalinijoshi19 — APPROVED** [review]

**Comment by RebeccaAnne** [comment]
> Is this just an iOS issue? @RebeccaAnne should have a peek here too !

I'm not fully grokking the nuance of these changes, but the crash from the bug looks like an iOS specific concern.

That said, I ran the bug payload through UWP, .NET, and JavaScript, and it doesn't look like it's rendering quite the same on all platforms.  UWP seems to bleed the show card into the show card padding, whereas the other two don't. @jwoo-msft what is this card supposed to look like?

UWP (note no emphasis padding around the show card):
image

JavaScript (emphasis border around the show card) (.NET is similar):
image

**Comment by jwoo-msft** [comment]
> > Is this just an iOS issue? @RebeccaAnne should have a peek here too !
> 
> I'm not fully grokking the nuance of these changes, but the crash from the bug looks like an iOS specific concern.
> 
> That said, I ran the bug payload through UWP, .NET, and JavaScript, and it doesn't look like it's rendering quite the same on all platforms. UWP seems to bleed the show card into the show card padding, whereas the other two don't. @jwoo-msft what is this card supposed to look like?

The card above can be condensed to the below. FYI, I added the snippet of this card to our Bleed.Comprehenisve.json.
```
		{
			"type":"TextBlock",
			"text":"REMOVED TEXT",
			"size":"ExtraLarge",
			"weight":"Bolder",
			"wrap":true
		},
		{
			"type":"ActionSet",
			"actions":[
			{
				"type":"Action.ShowCard",
				"title":"Results",
				"card":{
					"type":"AdaptiveCard",
					"$schema":"http://adaptivecards.io/schemas/adaptive-card.json",
					"body":[
					{
						"type":"Container",
						"items":[
							{
								"type":"Container",
								"items":[
								{
									"type":"TextBlock",
									"text":"REMOVED TEXT",
									"fontType":"Default",
									"size":"ExtraLarge",
									"spacing":"None",
									"weight":"Bolder",
									"wrap":true
								}
								],
								"style":"default"
							}
						],
						"style":"emphasis",
						"bleed":true
					}
					]
				}
			}
		]
		}

```
ActionSet ShowCard -> Container with emphasis style with bleed true -> Container with default style.
I don't think we have specified the bleed for showcard in ActionSet. If the parent card has a default style, then letting the container with emphasis to bleed is a possibility.

**Pull request merged**
