### PR TITLE
ios input evolution

### LINKED ISSUE #4420: [iOS][InputEvo] Input.Date validation interchanges month and day
# Platform

* iOS

# Version of SDK

feature/InputEvolution

# Details

Validation is affected by the input.date elements showing the date in the YYYY-DD-MM format that is different from other renderers. This behavior also affects validation.

Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-17 at 12 38 43

### LINKED ISSUE #4427: [iOS][InputEvo] Empty input number doesn't trigger isRequired validation
# Platform

* iOS

# Version of SDK

feature/inputEvolution

# Details

isRequired validation doesn't trigger for Input.Number when the input field is empty (ie, when an user has deleted the data that is in the field)

The card tested was Input.Number.ErrorMessage.json

Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-17 at 13 57 17

Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-17 at 13 57 21

### LINKED ISSUE #4428: [iOS][InputEvo] Compact Input.ChoiceSet not getting focus
# Platform

* iOS

# Version of SDK

feature/inputEvolution

# Details

When input validation fails and the first element to fail validation is a Compact ChoiceSet it should get focus but it currently doesn't. This may not be possible but Input.Date actually performs the focus behavior correctly

| Input.Date | Input.ChoiceSet | 
| --- | --- |
| Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-17 at 14 29 51 | Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-17 at 14 29 25 |

### LINKED ISSUE #4436: [iOS] [Input Validation] Input validation w/ hardware keyboard
# Platform

* iOS

# Version of SDK

feature/inputEvolution

# Details

Create an Input.Date, type some text using a hardware keyboard, don't click "Done" on the software keyboard, then click the submit action.

Screen Shot 2020-07-20 at 2 50 01 PM

Payload:
```
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2",
    "body": [
        {
            "type": "Input.Date",
            "isRequired": true,
            "min": "2020-07-10",
            "max": "2020-07-20",
            "id": "hi"
        }
    ],
    "actions": [
        {
            "type": "Action.Submit",
            "title": "Action.Submit"
        }
    ]
}
```

### LINKED ISSUE #4450: [iOS][Input Validation] Return warning if validation properties exist without an errorMessage
# Platform

* iOS

# Details

If the card author has set input validation properties but not set an errorMessage, return a warning to encourage the card author to add an errorMessage to provide more information to the user explaining why the input is invalid.

### PR DESCRIPTION
**Pull request by jwoo-msft**
## Related Issue
Added input validation and label #3081 
fixed #4420, fixed #4427, fixed #4428, fixed #4436, fixed #4450 

### Input validation and input label.
New ACRInputLabelView class holds input views.
Through the ACRInputLabelView, existing views' functions are extended to support validation, setting focus, displaying labels, and error message.
Input validation event is received at the ACRInputLabelView and passes down to appropriate event handler.
To support new showcard behavior, each showcard has an array of inputs, and showcards build a directed graph from child to parent showcard. Upon submission event, the showcard with the submit card travels the directed graph and collects input from the showcard at the vertex.
ChoiceSet's xib is updated and broken down to unchecked/checked and multi-select/single-select xibs to provide better customization experiences for customers.
Refactoring & code clean-up
### Bug Fixes
#4428
- rerouted set focus event to better handle the set focus event for compact choice set
#4427 
- made sure the parent's validation method is called on the number input type.
#4420 
- separated the dateFormatter to the encode dateFormatter and the decode dateFormatter, so the decode formatter is used for displaying the date, and encode formatter is used for collecting the data so that what's displayed and input and what's collected are in sync.
#4436
- Apple's calendar app disables the input field when a picker view is active. Made similar changes such that the text field is disabled when the picker view is active, so bogus inputs from h/w keyboard are prevented.

## How Verified
How you verified the fix, including one or all of the following: 
1. Bug bash.
2. Tested all 1.3 cards

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/4437)

### CODE REVIEW

**Comment by shalinijoshi19** [comment]
@jwoo-msft / @almedina-ms / @golddove what's the hold up to the review/merge here ?

**Comment by jwoo-msft** [comment]
> @jwoo-msft / @almedina-ms / @golddove what's the hold up to the review/merge here ?

I'm making one more refactoring.

**Pull request merged**
