### PR TITLE
[Android] Migrate to AndroidX

### LINKED ISSUE #4711: [Android]Complex layout will freeze when recyclerview merge to androidx
# Android

* Android

# Version of SDK

2.0.0

# Details

The sample demo is base on android support framework, but when recyclerview merge to androidx and load complex json, such as FlightDetails.json, it list will freeze and card view refresh the height repeatedly.
There have a sample demo [Sample.zip](https://github.com/microsoft/AdaptiveCards/files/5153594/Sample.zip)

### PR DESCRIPTION
**Pull request by golddove**
## Related Issue
Fixes #4711 

## Description
Migrate from deprecated support libraries to AndroidX.
The only upgrades in the library are:
`com.android.support:appcompat-v7:28.0.0` -> `androidx.appcompat:appcompat:1.0.0`
`com.android.support.constraint:constraint-layout:1.1.3` -> `androidx.constraintlayout:constraintlayout:1.1.3`

## How Verified
[Google says](https://developer.android.com/jetpack/androidx/migrate#prerequisites) these packages are binary equivalent to the new ones, and the only difference is in namespace.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/5648)

### CODE REVIEW

**Review by paulcam206 — APPROVED** [review]
Just for my info -- does this have any impact on existing customers of the Android package? In other words, will this require any changes on the part of hosts?

If no upstream impact, I think this is good :)

**Comment by golddove** [comment]
> Just for my info -- does this have any impact on existing customers of the Android package? In other words, will this require any changes on the part of hosts?
> 
> If no upstream impact, I think this is good :)

Yes, it impacts any hosts that are still using the old support libraries (which went out of support in 2018, so it is very uncommon). More discussion is in the linked issue - we confirmed with known partners that they're using AndroidX already. For them, there is no impact.

**Comment by paulcam206** [comment]
> > Just for my info -- does this have any impact on existing customers of the Android package? In other words, will this require any changes on the part of hosts?
> > If no upstream impact, I think this is good :)
> 
> Yes, it impacts any hosts that are still using the old support libraries (which went out of support in 2018, so it is very uncommon). More discussion is in the linked issue - we confirmed with known partners that they're using AndroidX already. For them, there is no impact.

ah -- sounds good. thanks! :)

**Comment by ThenAndNoThen** [comment]
The migration is not fully completed. We are still using flowbox 1.0.0, can we upgrade it to at least 1.1.0?

[androidFlexboxVersion](https://github.com/search?q=repo%3Amicrosoft%2FAdaptiveCards%20androidFlexboxVersion&type=code)

https://github.com/google/flexbox-layout/releases/tag/1.1.0

**Comment by ThenAndNoThen** [comment]
Filed a feature request: https://github.com/microsoft/AdaptiveCards/issues/8863

**Pull request merged**
