### PR TITLE
[WPF] Fix inline action crash

### LINKED ISSUE #4275: [WPF][Input Evolution] [Inline Submit Action Crash]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET WPF

# Version of SDK
feature/inputEvolution

# Details
**Payload**
https://github.com/microsoft/AdaptiveCards/blob/feature/inputEvolution/samples/v1.3/Elements/Input.Text.InlineAction.Label.json

Regression is observed; clicking on inline action crashes app

### PR DESCRIPTION
**Pull request by almedina-ms**
## Related Issue
Fixes #4275 

## Description
Links submit action to the list of submit action ids when rendering an inline action as it doesn't share the same rendering code as regular submit actions.

## How Verified
As can be seen below, the clicking an inline action doesn't crash anymore

WPFinlineActionFix

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/4290)

### CODE REVIEW

**Comment by shalinijoshi19** [comment]
@almedina-ms can you look at teh build failures with this change too? https://microsoft.visualstudio.com/AdaptiveCards/_build/results?buildId=24959952&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=dac0b392-2308-5704-b9f7-c5b20adf012e&l=528

**Comment by shalinijoshi19** [comment]
@paulcam206 thoughts on this failure for nodejs - https://microsoft.visualstudio.com/AdaptiveCards/_build/results?buildId=24959949&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=70b92200-87db-50c8-35f9-975ba5f9e5b7&l=26 ?

**Comment by shalinijoshi19** [comment]
@almedina-ms / @jwoo-msft there are iOS test errors with this build - are these known? https://microsoft.visualstudio.com/AdaptiveCards/_build/results?buildId=24959956&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=2671968b-90fa-5b72-8f77-dfefca30fe1e&l=221

**Comment by almedina-ms** [comment]
build errors are a known issue and they come from tests (except for js), when the platforms merge the feature branch errors should be solved

**Pull request merged**
