### PR TITLE
[JS][Renderer][Accessibility] Action.OpenUrl rendered buttons should have the "link" aria role

### PR DESCRIPTION
**Pull request by paulcam206**
# Details
Currently all actions get rendered as `<button>` elements with role "button". When a button opens a link, as is the case for `Action.OpenUrl`, it should have the "link" role instead.

**Important**
Just a note on the weirdness of this PR. I used a new tool to create this PR, which converted the issue into a PR rather than creating a new PR. I won't use it again, but it's why this looks weird. 👍 

# Description
Simple fix to have `OpenUrlAction` objects set `role="link"`.

# How verified
* Accessibility Insights
* F12 tools
* Tests (adding shortly)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/3914)

### CODE REVIEW

**Comment by shalinijoshi19** [comment]
@paulcam206 wasnt there an issue backing this PR?

**Comment by paulcam206** [comment]
> @paulcam206 wasnt there an issue backing this PR? I could have sworn this was an issue not a PR and it's gotten pretty confusing with the triage etc.. Whats going on here?

yep - as I noted in the description, I used a new tool to generate the PR not knowing that it would just convert the issue into a PR rather than create a new PR 😬

**Comment by paulcam206** [comment]
@dclaux approved over Teams

**Comment by shalinijoshi19** [comment]
@paulcam206 did this make it in to release/1.2 for 1.2.9 ? (sorry it missed my radar since it was converted to a PR and I'd been tracking issues)

**Comment by InduPriya1805** [comment]
@shalinijoshi19 Is this bug got fixed and changes are available in the latest release?

**Pull request merged**
