### PR TITLE
Add ability to customize toolbox titles (#3488)

### PR DESCRIPTION
**Pull request by dclaux**
## Related Issue
Backport fix for https://github.com/microsoft/AdaptiveCards/issues/3487 into release/1.2

## Description
Cherry-pick https://github.com/microsoft/AdaptiveCards/commit/4ea40b042ed8115327529c0031ffb77895534d4d into release/1.2

## How Verified
Verified manually in adaptivecards-designer-app

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/3489)

### CODE REVIEW

**Comment by dclaux** [comment]
Just a heads up that **I will merge ignoring the failures** here which are totally unrelated to my changes. Let me know if you have concerns about this.

**Comment by shalinijoshi19** [comment]
> Just a heads up that **I will merge ignoring the failures** here which are totally unrelated to my changes. Let me know if you have concerns about this.

That's fine the fixes that @nesalang / @almedina-ms / @paulcam206 have pulled in are still sitting inmy staging branch.

**Comment by shalinijoshi19** [comment]
> > Just a heads up that **I will merge ignoring the failures** here which are totally unrelated to my changes. Let me know if you have concerns about this.
> 
> That's fine the fixes that @nesalang / @almedina-ms / @paulcam206 have pulled in are still sitting inmy staging branch.

And they are in.

**Comment by dclaux** [comment]
Bypassing non NodeJS checks.

**Pull request merged**
