### PR TITLE
[Designer] Update peer button name from "X" to "Remove"

### PR DESCRIPTION
**Pull request by paulcam206**
## Related Issue
Fixes VSO #30909723

## Description
Simple change - button was titled `X`, but it should be more descriptive. I chose `Remove`.

## How Verified
* local build, narrator

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/5375)

### CODE REVIEW

**Comment by paulcam206** [comment]
ah - need to update role as well

**Review by dclaux — CHANGES_REQUESTED** [review]
I don't agree with this. The label doesn't need to be anything but an X, which is expressive enough and a known paradigm for "delete" or "remove" across many applications. Also, it is short which is preferable in this case where the horizontal space available to edit the key/value pair is limited.

If anything, the change should be:
- Make sure there's an accessible label on that button so that narrator doesn't just read X
- Allow for the text in that button to be configurable by the host app, by adding it (along with the accessible label mentioned above) to the resource strings

**Comment by dclaux** [comment]
To add to my comment above. If there was true justification in changing this "X" into "Remove", then there would also be justfified to change the "X" to close a window or dialog into "Close" - but that's not the case.

**Comment by paulcam206** [comment]
> To add to my comment above. If there was a real justification for changing this "X" into "Remove", then it would also be justified to change the "X" to close a window or dialog into "Close" - but that's not the case.

The alternative is to provide a means to paint `aria-label` independent of an `Action.Submit`'s `title`, which is probably spec-level work?

**Comment by RebeccaAnne** [comment]
> > To add to my comment above. If there was a real justification for changing this "X" into "Remove", then it would also be justified to change the "X" to close a window or dialog into "Close" - but that's not the case.
> 
> The alternative is to provide a means to paint `aria-label` independent of an `Action.Submit`'s `title`, which is probably spec-level work?

You could try to add something like this just in the designer and then log a bug for the "real work", sort of like what I did in #5277 (and logged #5356). Not the best approach maybe, but you might be able to decouple the designer accessibility work from the renderer feature.

**Comment by dclaux** [comment]
@paulcam206 just add an `accessibleLabel` property to the Action class and update the render logic to use it as the `aria-label`. Not talking about adding a schema property, just an internal public field that can only be used in code. This has been done multiple times already, like to disable Markdown processing on TextBlock via the `useMarkdown` property.

**Comment by RebeccaAnne** [comment]
> @paulcam206 just add an `accessibleTitle` property to the Action class and update the render logic to use it as the `aria-label`. Not talking about adding a schema property, just an internal public field that can only be used in code. This has been done multiple times already, like to disable Markdown processing on TextBlock via the `useMarkdown` property.

We probably still should log something to put it in the schema eventually though.

**Review by jwoo-msft — APPROVED** [review]

**Comment by paulcam206** [comment]
> > @paulcam206 just add an `accessibleTitle` property to the Action class and update the render logic to use it as the `aria-label`. Not talking about adding a schema property, just an internal public field that can only be used in code. This has been done multiple times already, like to disable Markdown processing on TextBlock via the `useMarkdown` property.
> 
> We probably still should log something to put it in the schema eventually though.

done! (#5383)

**Review by dclaux — APPROVED** [review]

**Pull request merged**
