### PR TITLE
Jwoo/release1.2

### PR DESCRIPTION
**Pull request by nesalang**
Merging fix for #3552 to release 1.2 branch

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/3608)

### CODE REVIEW

**Comment by shalinijoshi19** [comment]
@paulcam206 should we just delete some of the stale branches including 1.2 (stale and not used for 1.2 patch fixes)

**Comment by shalinijoshi19** [comment]
@paulcam206 let's also create an issue maybe for the sharedmodel-ci failure to track this in the PR's as we force-merge them using admin privileges :)

**Comment by paulcam206** [comment]
> @paulcam206 let's also create an issue maybe for the sharedmodel-ci failure to track this in the PR's as we force-merge them using admin privileges :)

#3609

**Comment by shalinijoshi19** [comment]
@nesalang go ahead and merge these over unless @paulcam206 would like to do a quick check and sign off :)

**Pull request merged**
