### PR TITLE
[JS] Make tabIndex on root card turnoffable

### LINKED ISSUE #2236: Focus is landing on non-interactive elements after activating the 'Show a simple' Adaptive cards button.
Please reference the following bug for repro steps and videos:
https://github.com/Microsoft/BotFramework-WebChat/issues/1340

### PR DESCRIPTION
**Pull request by paulcam206**
## Related Issue
Fixes #2236

## Description
Introduce new `GlobalSettings.setTabIndexAtCardRoot` option (for now, defaulted to `true` since that's the current behavior) that allows designer hosts to turn off setting `tabIndex=0` on root level card containers.

## How Verified
* local build
* made a local change to `source/nodejs/adaptivecards-site/themes/adaptivecards/layout/designer.ejs` and manually validated that `tabIndex` was no longer being set

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/4020)

### CODE REVIEW

**Comment by paulcam206** [comment]
@compulim -- FYI :)

**Comment by shalinijoshi19** [comment]
This is great turnaround @Paulcam206. Thanks! Btw have we also validated the changes here https://adaptivecardsci.z5.web.core.windows.net/pr/4020/designer?

**Comment by paulcam206** [comment]
> This is great turnaround @paulcam206. Thanks! Btw have we also validated the changes here https://adaptivecardsci.z5.web.core.windows.net/pr/4020/designer?

Since we've chosen to keep existing tabindex behavior on by default, you won't notice a difference in the PR build (at least not without a bunch of messing around in devtools).

**Pull request merged**
