### PR TITLE
Jwoo/release/1.2

### PR DESCRIPTION
**Pull request by nesalang**
## Related Issue
adding a tool that helps ios publishing to Cocoapods for 1.2 branch.

## Description
cherry-picked the to 1.2 branch from master since we may have more releases from 1.2 branch.

## How Verified
publishing has been tested with the tool few times.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/3492)

### CODE REVIEW

**Comment by shalinijoshi19** [comment]
@paulcam206, hmm another cert related failure for UWP release 1.2 ? 
<snip>
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(4353,5): Error APPX0105: Cannot import the key file 'UWPUnitTests_TemporaryKey.pfx'. The key file may be password protected. To correct this, try to import the certificate manually into the current user’s personal certificate store."
</snip>

**Comment by shalinijoshi19** [comment]
@nesalang can you work wtih @paulcam206 to figure out the UWP error.tx

**Comment by nesalang** [comment]
> @nesalang can you work wtih @paulcam206 to figure out the UWP error.tx

sure

**Pull request merged**
