### PR TITLE
New spacing model

### PR DESCRIPTION
**Pull request by dclaux**
See issue https://github.com/Microsoft/AdaptiveCards/issues/462

### CODE REVIEW

**Comment by dclaux** [comment]
FYI this is a **breaking change.** Separation in cards will stop working.

**Comment by danmarshall** [comment]
Will this breaking change happen across all platforms? I'm hoping that every platform will have the same featureset for the same number of major version. Also, at a breaking change, we should branch the existing code so that we can continue to fix bugs in the previous major version.

**Comment by danmarshall** [comment]
Perhaps this should not go to the master branch.

**Comment by dclaux** [comment]
Where else? It's already in its own branch (finalize-html)

**Comment by dclaux** [comment]
Yes, eventually all renderers will implement this change. We're starting with the HTML renderer as the reference implementation.
BTW are you suggesting I open a new master_v0.<some number> branch for this? We haven't reached v1 yet, so the assumption should be that there could still be breaking changes at this stage. So I was definitely simply going to push changes to master. If the WebChat control is using the NPM package (v0.6 being the latest), it won't break until we publish a new package and you decide to switch to using it. Do you think that's not good enough?

**Comment by danmarshall** [comment]
Yes, I suppose that master_v0 will suffice. And I don't anticipate there will be many bug fixes in it, but it is good to have in that case. Also true, the WebChat will depend on the NPM v0.6 and will not break.

The bigger issue is supporting our developers, many of whom will want to use the Visualizer for v0 and some will want to move ahead with v1. And they will need to know which of these versions is used in their WebChat, which they typically do not need to be aware of that dependency.

**Comment by dclaux** [comment]
Discussed offline with Dan. Since this is a breaking change, I'm closing this PR, will create a new branch and push my changes in there.

**Comment by dclaux** [comment]
I actually created a v0 branch that now represents the stable version of the pre v1 spec. All new changes will continue to be pushed to master which is the "working" (e.g. cutting edge) branch.

**Pull request merged**
