### PR TITLE
[iOS] fixed #4531

### LINKED ISSUE #4531: [iOS][RichTextBlock Rendering] [Parity issue in RichTextBlock TextRun with action]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Author or host

Host - Teamspace iOS

# Version of SDK

1.2.10

# Details

TextRun in a RichTextBlock with selectAction renders differently across clients with difference in text color and underline style.
Desktop:
Screenshot 2020-08-04 at 4 55 09 PM
iOS:
Screenshot 2020-08-04 at 6 15 04 PM

cardJSON:
```
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.2",
  "body": [
    {
      "type": "RichTextBlock",
      "inlines": [
        {
          "type": "TextRun",
          "text": "This is the first inline.",
          "selectAction": {
            "type": "Action.OpenUrl",
            "title": "Action.OpenUrl",
            "url": "http://adaptivecards.io"
          }
        }
      ]
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by jwoo-msft**
# Related Issue
Fixed #4531 

# Description

iOS sdk added underline to rich text block's select action. this change removes the link and applies default link color to match with the default presentation of the iOS link. The UIColor.link is applied when available, 13.0 above. If not available, the same hex value of the UIColor.link is used.

# Sample Card
https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.2/Tests/RichTextBlock.TextRun.SelectActions.json

# How Verified

How you verified the fix, including one or all of the following:
1. Unit tests are run
3. sample cards are run

Select actions with default foreground color and custom colors.
Screen Shot 2021-08-10 at 10 31 52 AM

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/6180)

### CODE REVIEW

**Review by paulcam206 — APPROVED** [review]

**Comment by golddove** [comment]
Android/JS seem to ignore foreground color for links in that same sample:

image

image

**Review by almedina-ms — APPROVED** [review]

**Comment by almedina-ms** [comment]
As a general question, is there consensus around having actions in text without an underline?

**Comment by jwoo-msft** [comment]
> As a general question, is there consensus around having actions in text without an underline?

we've decided in the design discussion that the format of the link should match the platform's default style.

**Comment by jwoo-msft** [comment]
> Android/JS seem to ignore foreground color for links in that same sample:
> 
> image
> 
> image

will match android/js

**Review by golddove — APPROVED** [review]

**Pull request merged**
