### PR TITLE
[Designer] Add help button and dialog

### PR DESCRIPTION
**Pull request by paulcam206**
## Related Issue
Fixes VSO 24095095

## Description
Add keyboard help toolbar button and dialog

Button:
image

Dialog:
image

## How Verified
* local build, dev tools, narrator

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/4849)

### CODE REVIEW

**Comment by golddove** [comment]
After closing the dialog w/ keyboard, the focus returns to the top of the page (above the UHF). Would it be possible to return focus to the help button?

**Comment by paulcam206** [comment]
> After closing the dialog w/ keyboard, the focus returns to the top of the page (above the UHF). Would it be possible to return focus to the help button?

yeah -- I'm going to have a separate PR for that. I also noticed tab navigation leaking out of the dialog, which is a broader bug that applies to all of our `Dialog`-derived experiences

**Review by RebeccaAnne — APPROVED** [review]
:shipit:

**Review by golddove — APPROVED** [review]

**Comment by paulcam206** [comment]
> > After closing the dialog w/ keyboard, the focus returns to the top of the page (above the UHF). Would it be possible to return focus to the help button?
> 
> yeah -- I'm going to have a separate PR for that. I also noticed tab navigation leaking out of the dialog, which is a broader bug that applies to all of our `Dialog`-derived experiences

fixes in #4850

**Pull request merged**
