### PR TITLE
[Android] Migrate deprecated support libraries to AndroidX

### LINKED ISSUE #4711: [Android]Complex layout will freeze when recyclerview merge to androidx
# Android

* Android

# Version of SDK

2.0.0

# Details

The sample demo is base on android support framework, but when recyclerview merge to androidx and load complex json, such as FlightDetails.json, it list will freeze and card view refresh the height repeatedly.
There have a sample demo [Sample.zip](https://github.com/microsoft/AdaptiveCards/files/5153594/Sample.zip)

### PR DESCRIPTION
**Pull request by golddove**
## Related Issue
Fixes #4711 

## Description
Android support libraries (e.g. AppCompat, etc.) are deprecated/not maintained (since 2018). They've all been renamed to androidx packages. This refactor performed as per https://developer.android.com/jetpack/androidx/migrate.

## How Verified
Manual testing

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/4477)

### CODE REVIEW

**Comment by shalinijoshi19** [comment]
@golddove is this ready for checkin or still draft?

**Comment by golddove** [comment]
This will be a breaking change, unfortunately. If we upgrade to the new libraries, every app that consumes our SDK also needs to upgrade to AndroidX.

We should check with current partners that are using our Android renderer. If everyone is already on AndroidX, then there should be no issue.

**Comment by shalinijoshi19** [comment]
@almedina-ms / @golddove what is the plan forward with moving to AndroidX?

**Comment by golddove** [comment]
Cisco has confirmed they are using AndroidX.

Waiting on a response from Teams.

What other major partners are using the Android SDK?

**Comment by paulcam206** [comment]
@golddove - are we still wanting this change?

**Comment by golddove** [comment]
Closing, outdated. Replaced by #5648

**Pull request closed without merging**
