### PR TITLE
Updated Maintainer Info

### PR DESCRIPTION
**Pull request by vivekvijayakrishnan**
Updated the React-Native and Pic2Card maintainer info.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/6300)

### CODE REVIEW

**Review by jonmill — COMMENTED** [review]
Should the source code in this repo be removed as well, since those files will not be updated any further?

**Comment by jonmill** [comment]
Should the pic2card build file also be removed?

**Comment by vivekvijayakrishnan** [comment]
Hi @jonmill,

We think removing the source code will confound the developers since all the previous versions of the react-native SDK point to the MS Adaptive card repo. After a couple of releases that point to the BigThinkCode Adaptive card fork repo, we can plan to remove the source code from here. Considering, Pic2Card has a dependency on the AdaptiveCard Designer UI, we will remove the source code in a separate PR after reviewing it with @matthidinger.

Moreover, removing the source code from the MS repo might cause issues while synching the new changes into our forked repo.

We prefer to handle this via a separate PR after releasing a few versions that point to the forked repo.

Please let us know your thoughts.

CC: @Vasanth-S

**Comment by vivekvijayakrishnan** [comment]
> @vivekvijayakrishnan - please also remove the pic2card YAML build files in the `.github/workflows` folder

We have fixed the build issues.

**Comment by jonmill** [comment]
@vivekvijayakrishnan - sounds good, we can remove the source code in a couple of months, no problems here. 

I still see the following files in the GitHub Actions folder, which should be removed since pic2card will not be built from this repo anymore

- .github/workflows/pic2card_build.yml
- .github/workflows/pic2card_docker_build_detr.yaml
- .github/workflows/pic2card_docker_build_rcnn.yaml

**Comment by vivekvijayakrishnan** [comment]
> @vivekvijayakrishnan - sounds good, we can remove the source code in a couple of months, no problems here.
> 
> I still see the following files in the GitHub Actions folder, which should be removed since pic2card will not be built from this repo anymore
> 
> * .github/workflows/pic2card_build.yml
> * .github/workflows/pic2card_docker_build_detr.yaml
> * .github/workflows/pic2card_docker_build_rcnn.yaml

Done 👍

**Review by jonmill — APPROVED** [review]
Looks great, thank you!

**Review by paulcam206 — APPROVED** [review]

**Pull request merged**
