### PR TITLE
Fix string/boolean parsing regression with null

### PR DESCRIPTION
**Pull request by dclaux**
## Related issue
Fixes https://github.com/microsoft/AdaptiveCards/issues/3436

Please refer to the issue for a full description of the problem.

## How verified
Verified manually (test card can be found here: https://github.com/microsoft/AdaptiveCards/blob/master/samples/v1.0/Tests/NullValuesAreAccepted.json)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/3437)

### CODE REVIEW

**Comment by shalinijoshi19** [comment]
Hey David, do we know when this was regressed? 1.2 or prior?

**Comment by shalinijoshi19** [comment]
Can you also include this payload as a test card in our samples folder - @rebeccaanne, can you help guide where such a card would exist? Thanks

---
In reply to: [530586405](https://github.com/microsoft/AdaptiveCards/pull/3437#issuecomment-530586405) [](ancestors = 530586405)

**Comment by RebeccaAnne** [comment]
I suppose since this applies to all versions, the [https://github.com/microsoft/AdaptiveCards/tree/master/samples/v1.0/Tests](https://github.com/microsoft/AdaptiveCards/tree/master/samples/v1.0/Tests) folder would be a good place to add this card. 

---
In reply to: [530586712](https://github.com/microsoft/AdaptiveCards/pull/3437#issuecomment-530586712) [](ancestors = 530586712,530586405)

**Comment by dclaux** [comment]
I unfortunately don't know when the regression was introduced. I have added the card to the samples folder.

**Comment by shalinijoshi19** [comment]
Thanks ; @dclaux, once you are able to do that please go ahead update the ##how verified section to include the reference to the new sample card created as well. (Also minor nit can you include the headings when you use the PR template for descriptions? ) THanks

---
In reply to: [530588425](https://github.com/microsoft/AdaptiveCards/pull/3437#issuecomment-530588425) [](ancestors = 530588425,530586712,530586405)

**Comment by shalinijoshi19** [comment]
Thanks - @RebeccaAnne, anything else that's needed here as part of adding hte new sample card? 

---
In reply to: [530590567](https://github.com/microsoft/AdaptiveCards/pull/3437#issuecomment-530590567) [](ancestors = 530590567)

**Comment by dclaux** [comment]
Done

**Comment by shalinijoshi19** [comment]
@paulcam206 what's up with hte failed .NET PR build ? Could you help? Tx

**Comment by shalinijoshi19** [comment]
Also @dclaux, you call it a "hotfix" where is this going to be patched to?

**Comment by dclaux** [comment]
I call it hotfix because it's a quick fix that is time sensitive given Teams needs it... it will be applied to master like any other fix.

**Comment by RebeccaAnne** [comment]
Ideally the new card would be run against the UWP test app to set baseline results. David, let me know if you'd like pointers on how to do that. Alternatively, we can log a bug to do that in a separate change.

---
In reply to: [530590809](https://github.com/microsoft/AdaptiveCards/pull/3437#issuecomment-530590809) [](ancestors = 530590809,530590567)

**Comment by shalinijoshi19** [comment]
> I call it hotfix because it's a quick fix that is time sensitive given Teams needs it... it will be applied to master like any other fix.

Hmm I see ; So for these issues, remember to use the Msft-TeamsIntegration label for now to the issue please _(I added it right now)_; Does Teams Web/Desktop pick up the latest greatest off of master or do they pull the released packages (my understanding was the latter); For patching we'd need to ensure we backport the changes but since npm is lagging way behind the other platforms anyways we'll be able to push this through as part of the Sept patch we are working towards end of this month. (So it would likely be version 1.2.3)

**Comment by paulcam206** [comment]
test failure due to new test card being added:

```
Starting test execution, please wait...
Failed   TestAllTestCards
Error Message:
 Test method AdaptiveCards.Test.AllPayloadTests.TestAllTestCards threw exception: 
System.AggregateException: One or more errors occurred. (Payload file failed: NullValuesAreAccepted.json) ---> System.Exception: Payload file failed: NullValuesAreAccepted.json ---> System.NullReferenceException: Object reference not set to an instance of an object.
Stack Trace:
    at AdaptiveCards.IgnoreDefaultStringEnumConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in C:\BA\795\s\source\dotnet\Library\AdaptiveCards\IgnoreDefaultStringEnumConverter.cs:line 40
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at AdaptiveCards.AdaptiveTypedElementConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in C:\BA\795\s\source\dotnet\Library\AdaptiveCards\AdaptiveTypedElementConverter.cs:line 100
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at AdaptiveCards.IgnoreEmptyItemsConverter`1.<>c__DisplayClass1_0.<ReadJson>b__1(JObject obj) in C:\BA\795\s\source\dotnet\Library\AdaptiveCards\IgnoreEmptyItemsConverter.cs:line 27
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at AdaptiveCards.IgnoreEmptyItemsConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in C:\BA\795\s\source\dotnet\Library\AdaptiveCards\IgnoreEmptyItemsConverter.cs:line 25
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at AdaptiveCards.AdaptiveTypedElementConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in C:\BA\795\s\source\dotnet\Library\AdaptiveCards\AdaptiveTypedElementConverter.cs:line 100
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at AdaptiveCards.IgnoreEmptyItemsConverter`1.<>c__DisplayClass1_0.<ReadJson>b__1(JObject obj) in C:\BA\795\s\source\dotnet\Library\AdaptiveCards\IgnoreEmptyItemsConverter.cs:line 27
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at AdaptiveCards.IgnoreEmptyItemsConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in C:\BA\795\s\source\dotnet\Library\AdaptiveCards\IgnoreEmptyItemsConverter.cs:line 25
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at AdaptiveCards.AdaptiveTypedElementConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in C:\BA\795\s\source\dotnet\Library\AdaptiveCards\AdaptiveTypedElementConverter.cs:line 100
   at AdaptiveCards.AdaptiveCardConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in C:\BA\795\s\source\dotnet\Library\AdaptiveCards\AdaptiveCardConverter.cs:line 54
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at AdaptiveCards.AdaptiveCard.FromJson(String json) in C:\BA\795\s\source\dotnet\Library\AdaptiveCards\AdaptiveCard.cs:line 247
   at AdaptiveCards.Test.AllPayloadTests.TestPayloadsInDirectory(String path, String[] excludedCards) in C:\BA\795\s\source\dotnet\test\AdaptiveCards.Test\AllPayloadTests.cs:line 55
--- End of inner exception stack trace ---
    at AdaptiveCards.Test.AllPayloadTests.TestPayloadsInDirectory(String path, String[] excludedCards) in C:\BA\795\s\source\dotnet\test\AdaptiveCards.Test\AllPayloadTests.cs:line 90
   at AdaptiveCards.Test.AllPayloadTests.TestAllTestCards() in C:\BA\795\s\source\dotnet\test\AdaptiveCards.Test\AllPayloadTests.cs:line 111
```

---
In reply to: [530592123](https://github.com/microsoft/AdaptiveCards/pull/3437#issuecomment-530592123) [](ancestors = 530592123)

**Comment by dclaux** [comment]
How can I __easily__ and __quickly__ test in the UWP test app?

**Comment by dclaux** [comment]
Teams pulls the nightly builds right now because they can't wait until we're ready to publish new packages.

**Comment by shalinijoshi19** [comment]
@RebeccaAnne / @paulcam can you work with David today to get him unblocked and as part of this let's document what it takes to add a new sample card and CI implications/troubleshooting.

---
In reply to: [530594077](https://github.com/microsoft/AdaptiveCards/pull/3437#issuecomment-530594077) [](ancestors = 530594077)

**Comment by dclaux** [comment]
If you don't mind I don't think there is a good reason to hold this PR. We can run the UWP test app separately. If it's OK with everyone, I will merge (and ignore the .NET error)

**Comment by paulcam206** [comment]
We can't have a new card that breaks CI checked in to the repo.

**Comment by shalinijoshi19** [comment]
> If you don't mind I don't think there is a good reason to hold this PR. We can run the UWP test app separately. If it's OK with everyone, I will merge (and ignore the .NET error)

Hey can you give folks some time to help figure this out? This will result in a build break as-is without addressing the CI break.

**Comment by dclaux** [comment]
I think the right thing to do for now is to remove the new test card to avoid the build break. We can add it back, along with whatever else needs to be done, as a separate issue/PR. How does that sound?

**Comment by RebeccaAnne** [comment]
> How can I **easily** and **quickly** test in the UWP test app?

[These instructions are for UWP, and will help us keep our UWP test app clean. This will **not** address the .NET CI issue (I can look into that in a minute)]

1. Open https://github.com/microsoft/AdaptiveCards/blob/master/source/uwp/AdaptiveCards.sln in Visual Studio.
2. Choose AdaptiveCardTestApp from the pulldown and run it (F5)
image
3. Click the "Cards" header to deselect all cards:
image
4. Scroll down and select your new card:
image
5. Click Start Test on the bottom of the test app.
6. The test app should show the rendered card as follows for each host config:
image
If the card shows an error, please log an issue against UWP to follow up (you can assign it to me). 
7. Whether or not the card renders, select "Accept all changes" at the top of the app:
image
8. Commit the generated files to github

**Comment by RebeccaAnne** [comment]
For the .NET break:

1. Open https://github.com/microsoft/AdaptiveCards/blob/master/source/dotnet/Test/AdaptiveCards.Test/AllPayloadTests.cs
2. In TestAllTestCards(), update the array of cards that is expected to fail to include your new card:
```
            TestPayloadsInDirectory(Path.Combine(SamplesPath, "v1.0", "tests"),
                new string[]
                {   
                    // These cards are expected to fail
                    "TypeIsRequired",
                    "AdaptiveCard.MissingVersion",
                    "NullValuesAreAccepted.json"
                });
```
3. **Log an issue against .NET for this card**

I'll let Shalini speak to whether she has a strong preference that the sample be part of this change or a separate one (although please log an issue if it doesn't go in with this). My only request would be that whenever it does go in, this .NET issue (and one against UWP if it also fails) are logged before the sample goes in so we don't lose track of it.

**Comment by RebeccaAnne** [comment]
> 1. **Log an issue against .NET for this card**
I logged #3439

**Pull request merged**
