### PR TITLE
Updated ExpenseReport to better align with blog post

### PR DESCRIPTION
**Pull request by jwoo-msft**
## Description
Update ExpenseReport card to use template more extensively.
* Changed such that each expense items to be generated by data.
* Made computation of expense items dynamic
* Added non-reimbursable item to demonstrated advanced use of AEL.
* Demonstrated template usage with toggle visibility.

## How Verified
1. made sure the card works as before.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/4041)

### CODE REVIEW

**Comment by matthidinger** [comment]
Thanks Joseph this is off to a great start, but there's still some "static" content in the template that to really sell the scenario should probably be moved to the data. E.g., the "Pending" status and "Trip to UAE", etc. Before closing this PR can we take another pass at moving all the dynamic stuff into the data and making the template a true template?

**Comment by jwoo-msft** [comment]
> Thanks Joseph this is off to a great start, but there's still some "static" content in the template that to really sell the scenario should probably be moved to the data. E.g., the "Pending" status and "Trip to UAE", etc. Before closing this PR can we take another pass at moving all the dynamic stuff into the data and making the template a true template?

Sure

**Comment by shalinijoshi19** [comment]
@jwoo-msft is this still a valid PR? If so lets get this checked in so it can be included in the website deployments (@matthidinger FYI.

**Comment by jwoo-msft** [comment]
> @jwoo-msft is this still a valid PR? If so lets get this checked in so it can be included in the website deployments (@matthidinger FYI.

I will check it in today

**Pull request merged**
