### PR TITLE
Cumulative ColumnSet fixes from Bug bash

### LINKED ISSUE #3007: [JS] Error on card with columnset, no columns, and a select action
# Platform

What platform is your issue or question related to? (Delete other platforms).

* JavaScript

# Issue

A columnSet without columns but with a selectAction causes an error on JavaScript (using the [visualizer ](https://adaptivecards-ci.azurewebsites.net/visualizer/index.html?hostApp=Bot%20Framework%20WebChat) to verify). Removing the select action or adding columns causes the card to render successfully as a blank card.

```json
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "ColumnSet",
            "selectAction": {
                "type": "Action.OpenUrl",
                "url": "https://adaptivecards.io/schemas/adaptive-card.json"
            }
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
}
```

Result:
image

### PR DESCRIPTION
**Pull request by dclaux**
Fixes #3007, #3009 
- Fix selectAction exception on empty ColumnSet (https://github.com/microsoft/AdaptiveCards/issues/3007)
- Hide horizontal overflow in ColumnSet (https://github.com/microsoft/AdaptiveCards/issues/3009)

Verified manually.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/3008)

### CODE REVIEW

**Comment by shalinijoshi19** [comment]
@dclaux / @RebeccaAnne are the issues that this 1.2 regressions? I am wondering about the "hotfix" portion of the PR here

**Comment by RebeccaAnne** [comment]
These were bug bash bugs. David would know for sure but I would guess they're not 1.2 regressions.

---
In reply to: [498330911](https://github.com/microsoft/AdaptiveCards/pull/3008#issuecomment-498330911) [](ancestors = 498330911)

**Comment by dclaux** [comment]
@shalinijoshi19 these are not regressions. But the issues were found immediately after publishing 1.2. It's just a PR name though, don't read too much into it. We can decide whether it makes sense to update the NPM package just for these or not.

**Comment by dclaux** [comment]
So here is an example of the NodeJS checks failing for no reason. There is nothing I can do about it, the checks passed right before I updated the branch from master with changes I didn't make. Yet, I can't merge.

**Comment by paulcam206** [comment]
> So here is an example of the NodeJS checks failing for no reason. There is nothing I can do about it, the checks passed right before I updated the branch from master with changes I didn't make. Yet, I can't merge.

The NodeJS failure is this:

```
##[command]"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'C:\BA\_temp\78bdaf92-422f-43f9-bb88-ca1cada56c7a.ps1'"
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1374 packages in 40.929s
npx: installed 1 in 3.845s
'prefix' is not recognized as an internal or external command,
operable program or batch file.
lerna notice cli v3.13.4
lerna info versioning independent
lerna info ci enabled
lerna info Bootstrapping 7 packages
lerna info Installing external dependencies
lerna ERR! npm install exited 4294963248 in 'adaptivecards-controls'
lerna ERR! npm install stderr:
npm ERR! path C:\BA\1663\s\source\nodejs\adaptivecards-controls\node_modules\fsevents\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall scandir
npm ERR! Error: EPERM: operation not permitted, scandir 'C:\BA\1663\s\source\nodejs\adaptivecards-controls\node_modules\fsevents\node_modules'
npm ERR!  { Error: EPERM: operation not permitted, scandir 'C:\BA\1663\s\source\nodejs\adaptivecards-controls\node_modules\fsevents\node_modules'
npm ERR!   stack: 'Error: EPERM: operation not permitted, scandir \'C:\\BA\\1663\\s\\source\\nodejs\\adaptivecards-controls\\node_modules\\fsevents\\node_modules\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'scandir',
npm ERR!   path: 'C:\\BA\\1663\\s\\source\\nodejs\\adaptivecards-controls\\node_modules\\fsevents\\node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\issblder\AppData\Roaming\npm-cache\_logs\2019-06-03T16_33_33_449Z-debug.log

lerna ERR! npm install exited 4294963248 in 'adaptivecards-controls'
lerna WARN complete Waiting for 6 child processes to exit. CTRL-C to exit immediately.
```

I'm not exactly sure why this happens (when it happens), but I've never seen it on my machine. It appears to be a transient config issue with the build host, so rerunning the pipelines can help. You can rerun pipelines on any PR by commenting this: `/azp run`

The .NET failure is this:

```
##[error]source\dotnet\Samples\WPFVisualizer.PackageProject\AdaptiveCards.Sample.WPFVisualizer.PackageProject.wapproj(35,3): Error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\DesktopBridge\Microsoft.DesktopBridge.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
Project "C:\BA\1\s\source\dotnet\AdaptiveCards.sln" (1) is building "C:\BA\1\s\source\dotnet\Samples\WPFVisualizer.PackageProject\AdaptiveCards.Sample.WPFVisualizer.PackageProject.wapproj" (13) on node 1 (default targets).
C:\BA\1\s\source\dotnet\Samples\WPFVisualizer.PackageProject\AdaptiveCards.Sample.WPFVisualizer.PackageProject.wapproj(35,3): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\DesktopBridge\Microsoft.DesktopBridge.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
Done Building Project "C:\BA\1\s\source\dotnet\Samples\WPFVisualizer.PackageProject\AdaptiveCards.Sample.WPFVisualizer.PackageProject.wapproj" (default targets) -- FAILED.
Done Building Project "C:\BA\1\s\source\dotnet\AdaptiveCards.sln" (default targets) -- FAILED.
```

Also guessing that this is a build host issue that will disappear on rerun.

**Comment by RebeccaAnne** [comment]
@paulcam206 is there a way to configure it to re-run on failure? If we have these sort of transient build machine failures it would be neat if it could try again and if it passed report it as a warning rather than an failure (and not block merging).

---
In reply to: [498354291](https://github.com/microsoft/AdaptiveCards/pull/3008#issuecomment-498354291) [](ancestors = 498354291)

**Comment by paulcam206** [comment]
I'm not aware of a way to set this up at the moment, and a quick search doesn't reveal anything too promising... :(

---
In reply to: [498356051](https://github.com/microsoft/AdaptiveCards/pull/3008#issuecomment-498356051) [](ancestors = 498356051,498354291)

**Pull request merged**
