### PR TITLE
[TS] Fix collapsed ShowCard losing input values

### PR DESCRIPTION
**Pull request by dclaux**
## Related Issue
Fixes https://github.com/microsoft/AdaptiveCards/issues/3617#event-2808512127

## Description
ShowCard was always re-rendered, losing the values in the `<input>` elements. This fix reuses the previously rendered ShowCard if possible.

## How Verified
Verified manually in adaptivecards-visualizer

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/3621)

### CODE REVIEW

**Comment by shalinijoshi19** [comment]
azp /run

**Comment by dclaux** [comment]
> azp /run

Not sure what that means?

**Comment by shalinijoshi19** [comment]
> > azp /run
> 
> Not sure what that means?

Baah; Forcing rerun except used the wrong syntax; The first error seems to be sporadic and wanted to see if a rerun would get it to succeed. (/azp run)

**Pull request merged**
