### PR TITLE
Add CodeQL Analysis workflow

### PR DESCRIPTION
**Pull request by jhutchings1**
Adds a GitHub Actions workflow that runs CodeQL on every push, and on a daily schedule.

Code scanning looks for vulnerabilities, such as XSS, SQL injection, etc., in your code. If it finds any new vulnerabilities it surfaces them in the PR as check annotations, and blocks the build until they’re fixed or marked as false positives. If it finds any on the repo’s default branch it displays them in the [security tab](../security/code-scanning).

For now you also need to be feature flagged individually to see results in the security tab (as well as having write permission on this repo) - if you drop an email to jhutchings1@github.com I can get anyone you need added. 

Finally, this is an early access program that has not been released yet, so please don't share before May 6th when we’re unveiling it at GitHub Satellite.

Cc: @greysteil

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/3964)

### CODE REVIEW

**Comment by greysteil** [comment]
Hey, there's a typo in this PR - the workflow file is nested under `.github/workflows/workflows` when it should be in `.github/workflows`. @jhutchings1 - can you get that fixed up for @paulcam206?

**Comment by jhutchings1** [comment]
I'm going to switch this back to draft while we confirm that the autobuilder works. Otherwise, I may need a little help figuring out the manual build steps for the (many!) languages in the repo :)

**Comment by paulcam206** [comment]
> I'm going to switch this back to draft while we confirm that the autobuilder works. Otherwise, I may need a little help figuring out the manual build steps for the (many!) languages in the repo :)

Happy to help :)

All of our code lives in subdirectories under `source`. The individual `README.md`s should theoretically contain build instructions. If they don't, are seemingly out of date, or just don't seem to work, LMK. All of our VS-based builds require VS2019.
* `android` → gradle based build. should be buildable on any platform with android & cmake tooling. 
  * `gradlew build`
* `community/reactnative` → you can skip this for now
* `dotnet` → most likely builds on Windows only (certainly some components are Windows only).
  * `msbuild AdaptiveCards.sln`
* `experimental` → skip this directory altogether :)
* `ios` → obviously requires MacOS to build.
  * `codebuild -sdk iphonesimulator -configuration Release -workspace .../source/ios/AdaptiveCards/AdaptiveCards.xcworkspace -scheme ADCIOSVisualizer -destination platform=iOS Simulator,name=iPhone 7,OS=10.3.1 build`
* `nodejs` → should build anywhere nodejs works. 
  * `npm i && npx lerna bootstrap && npx lerna run build`
  * I think this is the only platform where the autobuilder succeeds FWIW
* `shared/cpp/AdaptiveCardsSharedModel` → Windows only. 
  * `msbuild AdaptiveCardsSharedModel.sln`
* `tools` → skip this one
* `uwp` → Windows only. 
  * `msbuild AdaptiveCards.sln`
* `vscode` → skip
* `xamarin` → skip

@shalinijoshi19 FYI

**Comment by jhutchings1** [comment]
@paulcam Thanks for providing the additional detail here! Given the complexity of getting a build going, I'm happy to let your team riff on this. LEt me know if you need anything from my team around the analysis specifically though!

**Comment by paulcam206** [comment]
@jhutchings1 - I created a branch and authored a [codeql config](https://github.com/microsoft/AdaptiveCards/pull/3990/files) that builds most of our flavors (sans iOS, which may take longer to figure out). I've got a clean [run](https://github.com/microsoft/AdaptiveCards/actions/runs/97791361) of the codeql builds, but am not seeing any alerts. I suppose it's possible that there's nothing (I guess I don't really know what checkers are enabled by default), but at least for our NodeJS project, LGTM [shows a number](https://lgtm.com/projects/g/microsoft/AdaptiveCards?mode=list) of issues (though most are pretty minor). How can I verify that things are all wired up correctly?

**Comment by jhutchings1** [comment]
> @jhutchings1 - I created a branch and authored a [codeql config](https://github.com/microsoft/AdaptiveCards/pull/3990/files) that builds most of our flavors (sans iOS, which may take longer to figure out). I've got a clean [run](https://github.com/microsoft/AdaptiveCards/actions/runs/97791361) of the codeql builds, but am not seeing any alerts. I suppose it's possible that there's nothing (I guess I don't really know what checkers are enabled by default), but at least for our NodeJS project, LGTM [shows a number](https://lgtm.com/projects/g/microsoft/AdaptiveCards?mode=list) of issues (though most are pretty minor). How can I verify that things are all wired up correctly?

We've tuned the default rule set quite a bit so the noisier alerts that you would've seen in LGTM are off by default. As long as the actions run is completing successfully, it's doing what it's supposed to! 

Since you've got this one covered, I'm going to close my PR so there's no duplication.

**Pull request closed without merging**
