### PR TITLE
More designer fixes

### LINKED ISSUE #3178: [UWP] Visulizer throwing an futile error expecting number on strings
# Platform

* UWP

# Issue

This error is being thrown on the UWP visualizer although the Input.Text.Value should be a string not a number
image

This is an example of the json that would throw this error
```
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "Input.Text",
            "title": "New Input.Toggle",
            "placeholder": "Placeholder text",
            "id": "66",
            "isMultiline": true,
            "value": "hi"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
}
```

### LINKED ISSUE #3267: Designer puts title in Input.Text
# Issue

image

To reproduce:

1. Drag an Input.Text from the left toolbox onto the card
2. Observe the erroneous title field in the card's JSON

Expected:

Input.Text should not have a title field

### LINKED ISSUE #3301: IE11 buttons are squeezed
# Platform

* JavaScript

# Author or host

Host, rendering an Adaptive Card

# Version of SDK

1.2.0

# Issue

Browse to https://www.adaptivecards.io/visualizer/index.html using IE11. Buttons looks squeezed when using IE11.

image

A customer reported this bug on Web Chat repo https://github.com/microsoft/botframework-webchat/issues/2263 and mentioned a workaround.

> Found a workaround from #1836, it can be fixed with "$(".ac-pushButton").css("flex-basis", "");"

### LINKED ISSUE #3306: [Designer] In ChoiceSet, "Add a new choice" deletes titles of existing choices
# Platform

N/A

# Issue

If I have one or more existing choices listed using the designer, each with their own respective "title" fields, then clicking "Add a new choice," and then typing in something for the "Title" or "Value" field of this new choice (in the Element Properties tab) will cause the titles of existing choices to automatically disappear in the JSON.

```
{
            "type": "Input.ChoiceSet",
            "placeholder": "Placeholder text",
            "style": "expanded",
            "id": "asdf",
            "choices": [
                {
                    "title": "One",
                    "value": "choice1"
                },
                {
                    "title": "Two",
                    "value": "choice2"
                }
            ]
        }
```

Result:

```
{
            "type": "Input.ChoiceSet",
            "placeholder": "Placeholder text",
            "style": "expanded",
            "id": "asdf",
            "choices": [
                {
                    "value": "choice1"
                },
                {
                    "value": "choice2"
                },
                {
                    "title": "Three",
                    "value": "choice3"
                }
            ]
        }
```
(Typing in the Title or Value field automatically deletes the "title" of the previous choices)

### PR DESCRIPTION
**Pull request by dclaux**
Major designer update, plus fixes for:
- Fixes #3306 
- Fixes #3267 
- Fixes #3178 
- Fixes #3301 

Verified manually.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/3169)

### CODE REVIEW

**Comment by dclaux** [comment]
- Change erroneous "Maximum value" string into "Minimum value"
- Fix broken inlineAction and selectAction support

**Comment by shalinijoshi19** [comment]
> import * as markdownit from "markdown-it";

no changes? 

---
Refers to: source/nodejs/adaptivecards-designer-app/src/app.ts:4 in 506f138. [](commit_id = 506f138f15e41686da23bafef2797e82297e2ea6, deletion_comment = False)

**Comment by shalinijoshi19** [comment]
Can you add a "Fixes #<issue number>" line in the description ? Also a "How Verified" section real quick? thanks a ton!

---
In reply to: [510681619](https://github.com/microsoft/AdaptiveCards/pull/3169#issuecomment-510681619) [](ancestors = 510681619)

**Comment by dclaux** [comment]
Add fixes for:
- https://github.com/microsoft/AdaptiveCards/issues/3306
- https://github.com/microsoft/AdaptiveCards/issues/3267

**Comment by dclaux** [comment]
Add fix for:
- https://github.com/microsoft/AdaptiveCards/issues/3301

**Comment by shalinijoshi19** [comment]
For fixes syntax, i believe you have to prefix each issue fixed with a keyword (eg fixes #<>, fixes #<> or else the issues themselves dont get auto-closed. Please refer to https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by dclaux** [comment]
There isn't such a list. There is an issue open to replace "var" with "let" pretty much everywhere, which I do opportunistically (no real reason to address it all at once.)

There will be one (or two) big refactors needed to enable additional features going forward:
- One to allow a fully functional implementation of the version selector in the designer (an issue has already been raised for that feature: https://github.com/microsoft/AdaptiveCards/issues/3260)
- One to cleanup the parsing path in the renderer, which will likely be necessary for logging once we all agree on what needs to be logged

I do not know when I'll be able to do these though. The first one is a large amount of work and is risky.

**Comment by shalinijoshi19** [comment]
> There isn't such a list. There is an issue open to replace "var" with "let" pretty much everywhere, which I do opportunistically (no real reason to address it all at once.)
> 
> There will be one (or two) big refactors needed to enable additional features going forward:
> 
> * One to allow a fully functional implementation of the version selector in the designer (an issue has already been raised for that feature: #3260)
> * One to cleanup the parsing path in the renderer, which will likely be necessary for logging once we all agree on what needs to be logged
> 
> I do not know when I'll be able to do these though. The first one is a large amount of work and is risky.

Ok thanks. This is good to know and helpful context.

**Comment by dclaux** [comment]
The description is accurate, I list the issues that this PR fixes. Is there something else you'd like in there? I could describe what I actually did, but that'd be redundant with the code changes themselves.

**Comment by shalinijoshi19** [comment]
> The description is accurate, I list the issues that this PR fixes. Is there something else you'd like in there? I could describe what I actually did, but that'd be redundant with the code changes themselves.

Yes please. 
1. Fixing up the usage of the Fixes keyword to enable the github auto-closure logic to run 
2. Is there a way for each that you can summarize what was broken ? The changes should reflect how you fixed it, but not necessarily what was broken. _(it helps with this and potential reverts should they be needed at any point, if we can avoid bundling in too many disparate changes in one PR/commit) _
3. How Verified looks OK to me.

**Comment by shalinijoshi19** [comment]
Btw, you may want to update from master to pull in the latest and greatest and verify things still look good (looks like your branch is out of date with master).

**Comment by dclaux** [comment]
I have updated to uses the proper "fixes" syntax
The issues already describe what was broken, what else would you like to see in this PR?

**Comment by dclaux** [comment]
All my changes are unrelated to the UWP renderer and do not touch its codebase. I am ignoring the failure for that reason.

**Pull request merged**
