### PR TITLE
Add .NET templating alpha library

### LINKED ISSUE #3537: [.NET][Templating] API updates to align with JS
# Platform
* .NET

# Details

For API consistency across the [Templating SDKs](https://docs.microsoft.com/en-us/adaptive-cards/templating/sdk)

1. Rename `AdaptiveTransformer` to `AdaptiveTemplate`
2. Rename the method `Transform` to `Expand`
3. Add the ability to register custom functions. This is crucial during the early phases where we are still determining the baseline set of functions across the SDKs.

Here's the [custom function syntax](https://docs.microsoft.com/en-us/adaptive-cards/templating/sdk) in JS. The C# API should call into this;

```js
// Register a custom "add" function that adds two numbers
context.registerFunction(
    "add",
    (a, b) => {
        if (typeof a === "number" && typeof b === "number") {
            return a + b
        }
        else {
            return undefined;
        }
    }
)
```

### PR DESCRIPTION
**Pull request by andrewleader**
# Description
Fixes #3537 

Adds a .NET templating library. It's simply a wrapper on top of the JS library.

Added to the experimental folder so it doesn't impact anything else.

Note that it required updating the JS library webconfig to use `this` for it's `umd` configuration (so that it's usable both by browsers and node.js and native JS clients like .NET)

```csharp
AdaptiveTransformer transformer = new AdaptiveTransformer();

string jsonTemplate = @"{
	""type"": ""AdaptiveCard"",
	""version"": ""1.0"",
	""body"": [
		{
			""type"": ""TextBlock"",
			""text"": ""Hello, {person.firstName}!""
		}
	]
}";

string jsonData = @"{
	""person"": {
		""firstName"": ""Andrew"",
		""lastName"": ""Leader""
	}
}";

// The final JSON, it'll have "text": "Hello, Andrew!" in it!
string cardJson = transformer.Transform(jsonTemplate, jsonData);
```

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/3239)

### CODE REVIEW

**Comment by andrewleader** [comment]
@matthidinger @dclaux this is ready to go! With this, we'll have a .NET NuGet version of the templating library (using the JS library under the scenes), fully identical to what the JS library supports!

**Comment by matthidinger** [comment]
Checking this out now... I'd like to learn more about the umd issue before merging it in. We've got some many webpack configs and if at all possible I'd like to keep them consistent. Can you link to details or explain more about the issue it was hitting?

**Comment by matthidinger** [comment]
I think we can merge this PR in but I'd like to request some small changes:

For API consistency across the [Templating SDKs](https://docs.microsoft.com/en-us/adaptive-cards/templating/sdk)

1. Rename `AdaptiveTransformer` to `AdaptiveTemplate`
2. Rename the method `Transform` to `Expand`
3. Add the ability to register custom functions. This is crucial during the early phases where we are still determining the baseline set of functions across the SDKs.

Here's the [custom function syntax](https://docs.microsoft.com/en-us/adaptive-cards/templating/sdk) in JS. The C# API should call into this;

```js
// Register a custom "add" function that adds two numbers
context.registerFunction(
    "add",
    (a, b) => {
        if (typeof a === "number" && typeof b === "number") {
            return a + b
        }
        else {
            return undefined;
        }
    }
)
```

**Comment by shalinijoshi19** [comment]
@nesalang working on porting this and will open a separate PR for this. closing this one for now. @nesalang / @andrewleader / @matthidinger  FYI

**Pull request closed without merging**
