### PR TITLE
Use labels instead of text blocks for input choice set elements

### PR DESCRIPTION
**Pull request by PankajBhojwani**
# Related Issue

#6430 

# Description

The sample elements we had for input choice set were using text blocks instead of labels, making them inaccessible. This commit updates them to use labels instead.

# How Verified

Manual verification using accessibility insights. The combo boxes on the relevant samples now have accessible names.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/7100)

### CODE REVIEW

**Comment by PankajBhojwani** [comment]
This also resolves [24045031](https://microsoft.visualstudio.com/OS/_workitems/edit/24045031), tracked in #5655

**Comment by PankajBhojwani** [comment]
The `ios-ci.yml` check keeps failing, here is the log:

ADCIOSVisualizerUITests
  testCanGatherCorrectValuesFromChoiceset, Failed to synthesize event: Not hittable: Button, label: 'OK'
  /Users/runner/work/1/s/source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerUITests/ADCIOSVisualizerUITests.mm:298
  ```
    XCUIElementQuery *buttons = testApp.buttons;
    [buttons[@"OK"] tap];

  ```

  testCanGatherCorrectValuesFromCompactChoiceSet, Failed to get matching snapshot: No matches found for Elements matching predicate '"(null), Blue" IN identifiers' from input {(
  /Users/runner/work/1/s/source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerUITests/ADCIOSVisualizerUITests.mm:252
  ```
    XCUIElementQuery *tablesQuery = testApp.tables;
    [tablesQuery.cells[@"(null), Blue"].staticTexts[@"Blue"] tap];

  ```

  testCanGatherCorrectValuesFromExpandedRadioButton, Failed to synthesize event: Not hittable: Button, label: 'OK'
  /Users/runner/work/1/s/source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerUITests/ADCIOSVisualizerUITests.mm:277
  ```
    XCUIElementQuery *buttons = testApp.buttons;
    [buttons[@"OK"] tap];

  ```

  testCanGatherDefaultValuesFromChoiceInputSet, Failed to synthesize event: Not hittable: Button, label: 'OK'
  /Users/runner/work/1/s/source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerUITests/ADCIOSVisualizerUITests.mm:232
  ```
    XCUIElementQuery *buttons = testApp.buttons;
    [buttons[@"OK"] tap];

  ```

**Comment by PankajBhojwani** [comment]
The `ios-ci.yml` check keeps failing, here is the log:

ADCIOSVisualizerUITests
  testCanGatherCorrectValuesFromChoiceset, Failed to synthesize event: Not hittable: Button, label: 'OK'
  /Users/runner/work/1/s/source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerUITests/ADCIOSVisualizerUITests.mm:298
  ```
    XCUIElementQuery *buttons = testApp.buttons;
    [buttons[@"OK"] tap];

  ```

  testCanGatherCorrectValuesFromCompactChoiceSet, Failed to get matching snapshot: No matches found for Elements matching predicate '"(null), Blue" IN identifiers' from input {(
  /Users/runner/work/1/s/source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerUITests/ADCIOSVisualizerUITests.mm:252
  ```
    XCUIElementQuery *tablesQuery = testApp.tables;
    [tablesQuery.cells[@"(null), Blue"].staticTexts[@"Blue"] tap];

  ```

  testCanGatherCorrectValuesFromExpandedRadioButton, Failed to synthesize event: Not hittable: Button, label: 'OK'
  /Users/runner/work/1/s/source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerUITests/ADCIOSVisualizerUITests.mm:277
  ```
    XCUIElementQuery *buttons = testApp.buttons;
    [buttons[@"OK"] tap];

  ```

  testCanGatherDefaultValuesFromChoiceInputSet, Failed to synthesize event: Not hittable: Button, label: 'OK'
  /Users/runner/work/1/s/source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerUITests/ADCIOSVisualizerUITests.mm:232
  ```
    XCUIElementQuery *buttons = testApp.buttons;
    [buttons[@"OK"] tap];

  ```

**Review by paulcam206 — APPROVED** [review]

**Comment by paulcam206** [comment]
> The `ios-ci.yml` check keeps failing, here is the log:
> 
> ADCIOSVisualizerUITests testCanGatherCorrectValuesFromChoiceset, Failed to synthesize event: Not hittable: Button, label: 'OK' /Users/runner/work/1/s/source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerUITests/ADCIOSVisualizerUITests.mm:298
> 
> ```
>   XCUIElementQuery *buttons = testApp.buttons;
>   [buttons[@"OK"] tap];
> ```
> 
> testCanGatherCorrectValuesFromCompactChoiceSet, Failed to get matching snapshot: No matches found for Elements matching predicate '"(null), Blue" IN identifiers' from input {( /Users/runner/work/1/s/source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerUITests/ADCIOSVisualizerUITests.mm:252
> 
> ```
>   XCUIElementQuery *tablesQuery = testApp.tables;
>   [tablesQuery.cells[@"(null), Blue"].staticTexts[@"Blue"] tap];
> ```
> 
> testCanGatherCorrectValuesFromExpandedRadioButton, Failed to synthesize event: Not hittable: Button, label: 'OK' /Users/runner/work/1/s/source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerUITests/ADCIOSVisualizerUITests.mm:277
> 
> ```
>   XCUIElementQuery *buttons = testApp.buttons;
>   [buttons[@"OK"] tap];
> ```
> 
> testCanGatherDefaultValuesFromChoiceInputSet, Failed to synthesize event: Not hittable: Button, label: 'OK' /Users/runner/work/1/s/source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerUITests/ADCIOSVisualizerUITests.mm:232
> 
> ```
>   XCUIElementQuery *buttons = testApp.buttons;
>   [buttons[@"OK"] tap];
> ```

@jwoo-msft - can you chime in on how to get these tests updated?

**Comment by jwoo-msft** [comment]
> > The `ios-ci.yml` check keeps failing, here is the log:
> > ADCIOSVisualizerUITests testCanGatherCorrectValuesFromChoiceset, Failed to synthesize event: Not hittable: Button, label: 'OK' /Users/runner/work/1/s/source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerUITests/ADCIOSVisualizerUITests.mm:298
> > ```
> >   XCUIElementQuery *buttons = testApp.buttons;
> >   [buttons[@"OK"] tap];
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > testCanGatherCorrectValuesFromCompactChoiceSet, Failed to get matching snapshot: No matches found for Elements matching predicate '"(null), Blue" IN identifiers' from input {( /Users/runner/work/1/s/source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerUITests/ADCIOSVisualizerUITests.mm:252
> > ```
> >   XCUIElementQuery *tablesQuery = testApp.tables;
> >   [tablesQuery.cells[@"(null), Blue"].staticTexts[@"Blue"] tap];
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > testCanGatherCorrectValuesFromExpandedRadioButton, Failed to synthesize event: Not hittable: Button, label: 'OK' /Users/runner/work/1/s/source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerUITests/ADCIOSVisualizerUITests.mm:277
> > ```
> >   XCUIElementQuery *buttons = testApp.buttons;
> >   [buttons[@"OK"] tap];
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > testCanGatherDefaultValuesFromChoiceInputSet, Failed to synthesize event: Not hittable: Button, label: 'OK' /Users/runner/work/1/s/source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerUITests/ADCIOSVisualizerUITests.mm:232
> > ```
> >   XCUIElementQuery *buttons = testApp.buttons;
> >   [buttons[@"OK"] tap];
> > ```
> 
> @jwoo-msft - can you chime in on how to get these tests updated?



> > The `ios-ci.yml` check keeps failing, here is the log:
> > ADCIOSVisualizerUITests testCanGatherCorrectValuesFromChoiceset, Failed to synthesize event: Not hittable: Button, label: 'OK' /Users/runner/work/1/s/source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerUITests/ADCIOSVisualizerUITests.mm:298
> > ```
> >   XCUIElementQuery *buttons = testApp.buttons;
> >   [buttons[@"OK"] tap];
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > testCanGatherCorrectValuesFromCompactChoiceSet, Failed to get matching snapshot: No matches found for Elements matching predicate '"(null), Blue" IN identifiers' from input {( /Users/runner/work/1/s/source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerUITests/ADCIOSVisualizerUITests.mm:252
> > ```
> >   XCUIElementQuery *tablesQuery = testApp.tables;
> >   [tablesQuery.cells[@"(null), Blue"].staticTexts[@"Blue"] tap];
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > testCanGatherCorrectValuesFromExpandedRadioButton, Failed to synthesize event: Not hittable: Button, label: 'OK' /Users/runner/work/1/s/source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerUITests/ADCIOSVisualizerUITests.mm:277
> > ```
> >   XCUIElementQuery *buttons = testApp.buttons;
> >   [buttons[@"OK"] tap];
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > testCanGatherDefaultValuesFromChoiceInputSet, Failed to synthesize event: Not hittable: Button, label: 'OK' /Users/runner/work/1/s/source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerUITests/ADCIOSVisualizerUITests.mm:232
> > ```
> >   XCUIElementQuery *buttons = testApp.buttons;
> >   [buttons[@"OK"] tap];
> > ```
> 
> @jwoo-msft - can you chime in on how to get these tests updated?

I will defer the question to @almedina-ms since he updated these lines.

**Comment by almedina-ms** [comment]
@PankajBhojwani  @jwoo-msft 

For the iOS test issues it looks like something in the rendering process is being changed as the sample is being updated, @jwoo-msft may have more context on how the rendering changes, tests complain about some elements not being able to be found in the visual tree so code changes will have to be made to fix this issues

**Comment by jwoo-msft** [comment]
> @PankajBhojwani @jwoo-msft
> 
> For the iOS test issues it looks like something in the rendering process is being changed as the sample is being updated, @jwoo-msft may have more context on how the rendering changes, tests complain about some elements not being able to be found in the visual tree so code changes will have to be made to fix this issues

@almedina-ms,  looking at the code, it could be due to latency issue. when buttons are interacted to get the card, the line below assumes that card is rendered, but that may not be true as the inputs with label possible could render slower. https://github.com/microsoft/AdaptiveCards/blob/bff0aa0bb39af9237c667a84eb326f09588516f0/source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerUITests/ADCIOSVisualizerUITests.mm#L72

**Comment by jwoo-msft** [comment]
fixed the unit tests breakage via https://github.com/microsoft/AdaptiveCards/pull/7113

**Review by jwoo-msft — APPROVED** [review]
looks good

**Pull request merged**
