### PR TITLE
Update website with templating enabled by default

### PR DESCRIPTION
**Pull request by matthidinger**
**This is working PR and not intended to be merged until a more thorough review of the website changes**

## What is this?

The major changes in this PR add Templating support to the website. 

## Why?

This work is an attempt to increase awareness of templating based on the recent Community Call Survey where 45% of respondents said they had not heard of templating.

## Notable changes

* The Designer now has Templating enabled by default, including Sample Data Editor, etc
* Added Templating docs button Designer
* The Samples page got a major update to show "Template" samples
  * New Toggle button disables templating for customers not interested in it. This value will be saved to local browser storage
  * Clicking "Try it yourself" should load the template+sample data if templating is enabled. Otherwise it should load the non-templated Sample

## Try it

* https://adaptivecardsci.z5.web.core.windows.net/pr/3505/samples
* https://adaptivecardsci.z5.web.core.windows.net/pr/3505/samples/ActivityUpdate.html
* https://adaptivecardsci.z5.web.core.windows.net/pr/3505/samples/Restaurant.html
* https://adaptivecardsci.z5.web.core.windows.net/pr/3505/designer

## Known Issues

There are still some known issues and bugs that I will be closing shortly, but I wanted to get this out for early review since it's a relatively large change in the site.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/3505)

### CODE REVIEW

**Comment by dclaux** [comment]
I suppose it's OK for now to add yet another button to the toolbar as a quick way to allow feedback reporting, but there is very little space left in there... Have you considered other options?

**Comment by matthidinger** [comment]
Once the build finishes I'll send a link to take a look at it before we merge. In the recent commit I hid the full screen button in its place. I think it looks pretty good but let me know

**Comment by matthidinger** [comment]
Here it is, take a look: https://adaptivecardsci.z5.web.core.windows.net/pr/3505/designer

**Comment by matthidinger** [comment]
Also FYI, the environment variable change in this PR worked and vnext has been deployed :)

https://vnext.adaptivecards.io/designer/

**Comment by dclaux** [comment]
Cool, feedback button looks good.

**Pull request merged**
