### PR TITLE
Feature/Pic to Card integration

### PR DESCRIPTION
**Pull request by Davakumar**
Front end changes to integrate Pic2Card service, which generates adaptive card by uploading image using ML approach.
Currently Service is hosted at azure functioner:  https://ac-pic2card.azurewebsites.net/

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/3992)

### CODE REVIEW

**Comment by paulcam206** [comment]
looks like the build is failing in part because `package.json` has changes, but the associated `package-lock.json` changes aren't here

**Comment by Davakumar** [comment]
> @Davakumar / @matthidinger: looks like the build is failing in part because `package.json` has changes, but the associated `package-lock.json` changes aren't here

**Comment by Davakumar** [comment]
@paulcam206 Pushed the package-lock.json file. Kindly review.

**Comment by matthidinger** [comment]
Hey folks, I'm closing this PR and moving it to #3999 giving us a local branch to work in: `pic2card`

**Pull request closed without merging**
