### PR TITLE
A couple of site updates for accessibility

### PR DESCRIPTION
**Pull request by paulcam206**
## Related Issue
VSO #24112626
VSO #24113398

## Description
Two small changes:
* Change "Get Started" button role to `link` since it navigates the page
* Replace slider control on the "samples" page since it doesn't play nice with high contrast modes (invisible in HC White, and only partially visible in HC Black). Now we have a big checkbox instead:
image
(alt: screenshot of webpage updated to use a checkbox)

## How Verified
* local build and inspection with browser devtools

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/4155)

### CODE REVIEW

**Comment by shalinijoshi19** [comment]
> /azp run AdaptiveCards-SharedModel-CI, AdaptiveCards-.NET-PR, AdaptiveCards-NodeJS-Daily, AdaptiveCards-UWP-Daily-PRs, AdaptiveCards-Android-CI, AdaptiveCards-iOS-CI

@paulcam206 I've just created a new [fabricbot](https://aka.ms/fabricbotconfig) rule to add this for new PRs or when updates are pushed to existing PRs. Let me know if this isn't working as expected.

**Comment by shalinijoshi19** [comment]
> Hi @paulcam206. Thanks for helping make the AdaptiveCards JS renderer + tooling better. As additional verification, once the JS build succeeds, please go to the [test site](https://adaptivecardsci.z5.web.core.windows.net/pr/4155) to test out your website/designer changes.

Thanks I actually verified on this test build and it looks like it's updated with the PR build results.

**Comment by paulcam206** [comment]
> > /azp run AdaptiveCards-SharedModel-CI, AdaptiveCards-.NET-PR, AdaptiveCards-NodeJS-Daily, AdaptiveCards-UWP-Daily-PRs, AdaptiveCards-Android-CI, AdaptiveCards-iOS-CI
> 
> @paulcam206 I've just created a new [fabricbot](https://aka.ms/fabricbotconfig) rule to add this for new PRs or when updates are pushed to existing PRs. Let me know if this isn't working as expected.

It looks like fabricbot doesn't have permissions to trigger builds. If we want to trigger builds automatically, I can change our PR triggers to do that :)

**Comment by shalinijoshi19** [comment]
> > > /azp run AdaptiveCards-SharedModel-CI, AdaptiveCards-.NET-PR, AdaptiveCards-NodeJS-Daily, AdaptiveCards-UWP-Daily-PRs, AdaptiveCards-Android-CI, AdaptiveCards-iOS-CI
> > 
> > 
> > @paulcam206 I've just created a new [fabricbot](https://aka.ms/fabricbotconfig) rule to add this for new PRs or when updates are pushed to existing PRs. Let me know if this isn't working as expected.
> 
> It looks like fabricbot doesn't have permissions to trigger builds. If we want to trigger builds automatically, I can change our PR triggers to do that :)

Ha! Good point there -- I am trying to find a balance between the "All or nothing" here -- The guidance from AzureDevOps at the moment seems to be to be conservative with using shared/pool resources (even if private) -- How can we make this manual rerun easier for the dev inner loop without going overboard with the build resource usage? For the manual scenario, when do we want the builds to be triggered? each new non-spec PR? do we want the builds to run for every subsequent commit to the PR?

**Pull request merged**
