### PR TITLE
Revert "[Android] Use ConstraintLayout for Image sizing (#4461)"

### LINKED ISSUE #4518: [Android][Images are either missing or too small]
# Platform

* Android

# Version of SDK

20.07

# Details

* [ActivityUpdate.json](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.0/Scenarios/ActivityUpdate.json) doesn't have the profile picture.
* [FlightItinerary.json](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.0/Scenarios/FlightItinerary.json) has a very small image.
* [WeatherCompact.json](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.0/Scenarios/WeatherCompact.json) doesn't have the weather image.
* [ProductVideo.json](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.0/Scenarios/ProductVideo.json) doesn't have the poster.
* [ExpenseReport.json](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.2/Scenarios/ExpenseReport.json) doesn't have chevrons that toggle subviews. It appears that an image view is missing since the view handles the touch event. 

Screenshot_20200731-170555

Screenshot_20200731-171520

### PR DESCRIPTION
**Pull request by almedina-ms**
## Related Issue
Fixes #4518 

## Description
This reverts commit 805c51e0d28fc2ca8ff49ae311e0f9e85bea6f7d.

Up to this point the media element still doesn't work, going back I was able to revert the break by going to commit 120219157cc913cfde7a7cf35ff87e9405c30020 for ImageRenderer

## How Verified
TBD

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/4520)

### CODE REVIEW

**Comment by almedina-ms** [comment]
> Thanks for this.
> 
> Reverting #4461 seems to fix the media issue when I test it (the one about casting from constraint params). What further issue did you see / what was the fix?

the other issue was horizontal alignment that is now fixed, but we're missing some testing

**Comment by shalinijoshi19** [comment]
@golddove this gets CP'd into release/20.07 && release/1.2 as well yeah?

**Comment by shalinijoshi19** [comment]
> > Thanks for this.
> > Reverting #4461 seems to fix the media issue when I test it (the one about casting from constraint params). What further issue did you see / what was the fix?
> 
> the other issue was horizontal alignment that is now fixed, but we're missing some testing

What is the testing here and can we include the test cards in if they aren't already part of the initial fixes?

**Comment by shalinijoshi19** [comment]
This needs to be CP'd over to release/1.2 and release/20.07 @almedina-ms thanks

**Pull request merged**
