### PR TITLE
User/shalinijoshi19/v1.2.6

### PR DESCRIPTION
**Pull request by shalinijoshi19**
## Related Issue
At this point includes commits for this [query](https://github.com/microsoft/AdaptiveCards/issues?q=is%3Aissue+label%3A%22AdaptiveCards+v1.2.6%22+is%3Aclosed).
All the remaining ones should go directly into release/1.2 at this point in time.

## Description
[CherryPicks] Picking up changes for AdaptiveCards 1.2.6 patch release

## How Verified
Pending collective bug bash on this branch 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/3747)

### CODE REVIEW

**Comment by shalinijoshi19** [comment]
@nesalang there were some merge conflicts I'd needed to resolve here. Please double check the changes look accurate. Reminder (@almedina-ms , @nesalang )  for next time to please fix the bugs first in release/1.2 and then cherry-pick into master. Although to be fair, some of these weren't targeted for 1.2.6 originally so made sense that we'd fix in master first.

**Comment by shalinijoshi19** [comment]
Also @nesalang looks like we have a bad merge (the iOS build is failing) - could you take a look? THanks!

**Comment by shalinijoshi19** [comment]
@almedina-ms do we need to update the Android package version here?

**Comment by almedina-ms** [comment]
Android package version is retrieved from the custom.props file, I don't see it in the file list so yes, it must be updated

---
In reply to: [579193011](https://github.com/microsoft/AdaptiveCards/pull/3747#issuecomment-579193011) [](ancestors = 579193011)

**Comment by shalinijoshi19** [comment]
> Android package version is retrieved from the custom.props file, I don't see it in the file list so yes, it must be updated
> 
> In reply to: [579193011](https://github.com/microsoft/AdaptiveCards/pull/3747#issuecomment-579193011) [](ancestors = 579193011)

ok thanks. I've updated it; @nesalang, what is needed now to check this in?

**Comment by nesalang** [comment]
> > Android package version is retrieved from the custom.props file, I don't see it in the file list so yes, it must be updated
> > In reply to: [579193011](https://github.com/microsoft/AdaptiveCards/pull/3747#issuecomment-579193011) [](ancestors = 579193011)
> 
> ok thanks. I've updated it; @nesalang, what is needed now to check this in?

@shalinijoshi19 
From iOS side, everything is checked-in. I will double check android & iOS. Could we add some test json files to this branch only for today's bug bash, or would it be better to create a PR on master branch as well?

**Comment by shalinijoshi19** [comment]
> > > Android package version is retrieved from the custom.props file, I don't see it in the file list so yes, it must be updated
> > > In reply to: [579193011](https://github.com/microsoft/AdaptiveCards/pull/3747#issuecomment-579193011) [](ancestors = 579193011)
> > 
> > 
> > ok thanks. I've updated it; @nesalang, what is needed now to check this in?
> 
> @shalinijoshi19
> From iOS side, everything is checked-in. I will double check android & iOS. Could we add some test json files to this branch only for today's bug bash, or would it be better to create a PR on master branch as well?

We should be able to add json files as long as we run the UWP Test app to go with it so as not to break CI !

**Comment by shalinijoshi19** [comment]
@nesalang, am going ahead merging this branch in now!

**Comment by nesalang** [comment]
> @nesalang, am going ahead merging this branch in now!

will produce the sample apps now.

**Pull request merged**
