### PR TITLE
[TS] Input validation

### PR DESCRIPTION
**Pull request by dclaux**
## Related Issue
Fixes https://github.com/microsoft/AdaptiveCards/issues/3081

## Description
This PR implements input validation/input labels in the JS renderer. The implementation leverages the work that had already been done for 1.2 with changes according to the final spec.

This PR also includes designer support.

**Notes:**
I have discussed the below with Alberto and we agreed that these changes made sense. If there is a need to further discuss, I'm happy to take it offline.
- This implementation uses property names in HostConfig that differ from those used in the spec. The spec will be updated to match the terminology used in this implementation. Namely, the code uses this format:
```json
"inputs": {
	"label": {
		"inputSpacing": "small",
		"requiredInputs": {
			"suffix": "*",
			"suffixColor": "attention",
			"weight": "default",
			"color": "default",
			"size": "default",
			"isSubtle": false
		},
		"optionalInputs": {
			"color": "default",
			"weight": "default",
			"size": "default",
			"isSubtle": false
		}
	},
	"errorMessage": {
		"spacing": "small",
		"size": "default",
		"weight": "lighter",
		"color": "attention"
	}
}
```
- This implementation includes the `suffixColor` property which goes one step beyond the spec. I felt that this was necessary as I implemented the feature. I can always remove it, but I really do think we need to support it.

## How Verified
Verified manually in the designer.

Sample test payload:
```json
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "body": [
        {
            "type": "Input.Text",
            "placeholder": "Placeholder text",
            "label": "This is an optional input",
            "id": "input1"
        },
        {
            "type": "Input.Text",
            "placeholder": "Placeholder text",
            "errorMessage": "The input value is invalid. This error message is intentionally long to show that it wraps.",
            "isRequired": true,
            "id": "input2",
            "regex": "abc",
            "label": "This is a required Text input. This label is intentionally long to show that it correctly wraps."
        },
        {
            "type": "Input.Date",
            "label": "This is a required Date input",
            "isRequired": true,
            "min": "6/1/2020",
            "max": "6/30/2020",
            "errorMessage": "The input value is invalid. This error message is intentionally long to show that it wraps.",
            "id": "input3"
        },
        {
            "type": "Input.Time",
            "label": "This is a required Time input",
            "isRequired": true,
            "min": "08:00",
            "max": "15:00",
            "errorMessage": "The input value is invalid. This error message is intentionally long to show that it wraps.",
            "id": "input4"
        },
        {
            "type": "Input.Number",
            "placeholder": "Placeholder text",
            "label": "This is a required Number input",
            "isRequired": true,
            "errorMessage": "The input value is invalid. This error message is intentionally long to show that it wraps.",
            "min": 4,
            "max": 6,
            "id": "input5"
        },
        {
            "type": "Input.ChoiceSet",
            "choices": [
                {
                    "title": "Choice 1",
                    "value": "Choice 1"
                },
                {
                    "title": "Choice 2",
                    "value": "Choice 2"
                }
            ],
            "placeholder": "Placeholder text",
            "label": "This is a required ChoiceSet input",
            "isRequired": true,
            "errorMessage": "The input value is invalid. This error message is intentionally long to show that it wraps.",
            "id": "input6"
        },
        {
            "type": "Input.Toggle",
            "title": "New Input.Toggle",
            "label": "This is a required Toggle input",
            "isRequired": true,
            "errorMessage": "The input value is invalid. This error message is intentionally long to show that it wraps.",
            "id": "input7"
        }
    ],
    "actions": [
        {
            "type": "Action.Submit",
            "title": "Action.Submit"
        }
    ]
}
```

As initially rendered:
image

Once the action is clicked, showing validation errors:
image

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/4185)

### CODE REVIEW

**Comment by shalinijoshi19** [comment]
@dclaux unsure if it's the sample card or the actual implementation but hte behavior with omitting the required fields results in this Action.Submit behavior - is this what we want? 

Also, what does it mean to have a Toggle Input be required? What if I don't want to select it? 

image

**Comment by dclaux** [comment]
This is per spec... when you hit an action button inputs gets validated and any input that fails validation is highlighted with the corresponding error message displayed under it. A required Input.Toggle must be checked to be valid.

**Comment by dclaux** [comment]
@shalinijoshi19 And if your question relates to why the error messages read "The input value isn't valid. The input value isn't valid. The input value isn't valid. The input value isn't valid. The input value isn't valid." that is because that's the error message as specified in the card payload.

**Comment by shalinijoshi19** [comment]
> @shalinijoshi19 And if your question relates to why the error messages read "The input value isn't valid. The input value isn't valid. The input value isn't valid. The input value isn't valid. The input value isn't valid." that is because that's the error message as specified in the card payload.

Thanks @Dclaux. Yes I was curious about the multiple error messages and had missed seeing that it was part of the payload and not some error handler triggering multiple times! Thanks for fixing the payload. 

Btw @dclaux this needs to land in the inputEvolution  feature branch feature/inputEvolution

**Comment by shalinijoshi19** [comment]
@dclaux per discussion offline, can you actually also push this sample esp with the wrapping text case checked into the inputs feature branch? Thanks

**Comment by shalinijoshi19** [comment]
@paulcam206 is "/azp run" supposed to work still for manual reruns? What are the cases where we'd need to invoke it again outside of retrying failed runs?

**Comment by dclaux** [comment]
Closing this PR against `main`, will reopen against `feature/inputEvolution`

**Comment by paulcam206** [comment]
for future reference, you can retarget a PR by clicking the "Edit" button at the top. screenshot from a different PR:

image
(alt: screenshot showing editable base branch at top of PR form)

**Pull request closed without merging**
