### PR TITLE
Switch visualizer editor from Ace to Monaco

### PR DESCRIPTION
**Pull request by dclaux**
Monaco is the editor used in VS Code. Among other things, it supports IntelliSense which will make it easier to author cards.

https://microsoft.github.io/monaco-editor/index.html

### CODE REVIEW

**Comment by QingpingMeng** [comment]
Going back/forward button doesn't re-render the card using correct theme

**Comment by dclaux** [comment]
That likely was already the case before, but I'll take a look.

**Comment by QingpingMeng** [comment]
otherwise it looks good to me

**Comment by dclaux** [comment]
Navigation is fixed

**Comment by dclaux** [comment]
The code hasn't changed, it's the exact same but now hooked up to the Monaco editor. sessionStorage.getItem/setItem was throwing an exception for a reason I don't understand.

The difference is Monaco load asynchronously (to be honest it's real not that easy to code against, Ace was a lot better) when Ace initializes synchronously. The code to re-load the previous payload was in the callback that is invoked after Monaco has finished initializing; I moved it out, and it now works.

I do not know why the schema won't load. I will look into this next week.

**Comment by dclaux** [comment]
It's very possible that this is simply a cross domain request problem, since the schema is hosted on adaptivecards.io

**Comment by QingpingMeng** [comment]
it looks good to me

**Comment by matthidinger** [comment]
The visualizer looks good. Seems some parts of the schema aren't compatible with their IntelliSense provider though -- everything in body isn't registering for me. the `actions` array works as expected though.  Feel free to merge, will have to investigate that stuff in a later PR

**Comment by dclaux** [comment]
Correct - the schema doesn't seem to be up to date/finalized. I haven't touched it in this PR. I will merge these changes.

**Pull request merged**
