### PR TITLE
Reactnative/release 1.2.2

### PR DESCRIPTION
**Pull request by IbrahimSulai**
Updated the version number

### CODE REVIEW

**Comment by BalajiR** [comment]
@dclaux , This PR is just for updating the version number for npm package release. The job `AdaptiveCards-NodeJS-Daily` is failed. Can you please help us in getting the details ? Thanks.

**Comment by dclaux** [comment]
@BalajiR this error happens sporadically and I unfortunately do not not know what causes it. @matthidinger can you help?

**Comment by matthidinger** [comment]
Sorry about that folks, it's all good now. In the future you should be able to add a comment with `/azp run` which should re-run builds in case this happens again.

**Comment by IbrahimSulai** [comment]
> Sorry about that folks, it's all good now. In the future you should be able to add a comment with `/azp run` which should re-run builds in case this happens again.

Sure @matthidinger, we will add this comment if this happens in future.
@matthidinger and @dclaux - Thanks for the quick response.

**Pull request merged**
