### PR TITLE
[JS] Media element support

### PR DESCRIPTION
**Pull request by dclaux**
This PR implements https://github.com/Microsoft/AdaptiveCards/issues/196 and https://github.com/Microsoft/AdaptiveCards/issues/1361

Notes:
- **HostConfig.playButton isn't supported**: a better experience is achieved with native styling via CSS
- **HostConfig.maxMediaSize isn't supported**: as far as I can tell, there is no way to retrieve the size of the actual stream for several reasons:
  - I can't know which stream from the sources will be picked by the Media control (since it depends on the codecs installed on the machine)
  - Determining the size of the stream would require making a HEAD request on the stream's URL which would generate a cross-domain error anyway

Here is what things look like in Chrome (note that all browsers have their own UI for controls).
image

Notes:
- The default Play button is somewhat customizable in CSS and is designed to mimic Chrome's media player button, which provides for a smooth transition between the poster and the actual player.
- When the is no poster, the background is also customizable in CSS.

Once video is playing (controls disappear once mouse is idle or moves out of the player's box):
image

Audio player works just the same. Here is what it looks like while playing in Chrome:
image

When inline playback isn't allowed, the host application can handle the static **Media.onPlay** event.

### CODE REVIEW

**Comment by andrewleader** [comment]
Great screenshots, thanks David!

@matthidinger I kinda agree that it's okay the HostConfig playButton isn't supported... if hosts are customizing, they probably would want to use CSS rather than an image which doesn't scale well.

@RebeccaAnne on UWP were you able to implement the HostConfig maxMediaSize? I'm curious if anyone was able to implement that. If not, it should just be removed.

**Comment by matthidinger** [comment]
Looks good, thanks David!

**Comment by tuanh118** [comment]
I think for an audio with poster, it should display the static poster image while the audio is playing.

**Comment by dclaux** [comment]
If that's what we want then I'd say that playback controls should always appear below the poster for Audio, with no default play button overlay. The `<audio>` tag can be made to only load metadata or no data at all until the play button is pressed.

**Pull request merged**
