### PR TITLE
[JS] Updated deprecated usage of keycode to code (#5837)

### LINKED ISSUE #5837: [JS] Replace `keyCode` with `code` everywhere
# Target Platform

JS

# Problem Description

`KeyboardEvent.keyCode` is deprecated. Applications should use `KeyboardEvent.code` instead. The JS SDK still uses `keyCode` in some places; these should be updated.

### PR DESCRIPTION
**Pull request by ChristoperHowell**
# Related Issue
Fixes #5837 

# Description

It has been identified that at various locations the deprecated keycode property was in use. This has been updated to use the code property instead.

# How Verified

1. Built locally
2. Tested key commands on image element with select action
3. Tested key commands on media element

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/5997)

### CODE REVIEW

**Comment by paulcam206** [comment]
Thanks for the PR, @ChristoperHowell 👍 

Taking a look now :)

**Review by paulcam206 — APPROVED** [review]
looks good -- @dclaux?

**Review by dclaux — CHANGES_REQUESTED** [review]
Looks good, but there are more uses of `code` in the designer code base that should also be updated (technically there are quite a few more in the adaptivecards-controls package as well but it's less important to update at this time)

**Comment by ChristoperHowell** [comment]
Hi, @dclaux. I originally searched for keycode using VS code. This is what came back and I have fixed them. Would you be able to point me in the right direction to find more occurrences?

**Comment by dclaux** [comment]
@ChristoperHowell the other references are in the designer code base, which lives in the `source\nodejs\adaptivecards-designer` folder.

**Comment by ChristoperHowell** [comment]
Thanks for the reply @dclaux. I’ve manually checked every file in the designer project and can find no other occurrences of the deprecated key code property. 

From my understanding, the original issue requested that all occurrences of the deprecated key code property be updated to use the code property, which I have done this. Was there an additional requirement, or did I make a mistake in my understanding of this request? I can find other event properties being used such as the event shift key property. Would you like these modified to use the event code property?

Thanks for the input!

**Comment by dclaux** [comment]
@ChristoperHowell my apologies. I do not know what I typed in the search box, but I must have typed something else than "keyCode", as I'm now not finding the references I mentioned before. Or maybe I just dreamt them.

Either way, your changes look good, so I'll go ahead and approve your PR then merge.

Thank you very much for this contribution!

**Review by dclaux — APPROVED** [review]

**Comment by ChristoperHowell** [comment]
@dclaux, not a problem! Thanks for letting me contributed!

**Pull request merged**
