### PR TITLE
[TS] Fix horizontalAlignment parsing bug

### PR DESCRIPTION
**Pull request by dclaux**
Implements the following:
- https://github.com/Microsoft/AdaptiveCards/issues/861
- https://github.com/microsoft/adaptivecards/issues/1078
- https://github.com/microsoft/adaptivecards/issues/1978
- https://github.com/Microsoft/AdaptiveCards/issues/1886
- Bug fixes

All manually tested.

### CODE REVIEW

**Comment by shalinijoshi19** [comment]
@PaulCam is added to the review. #Closed

**Comment by shalinijoshi19** [comment]
Could we add the following sections to teh Description real quick:
Problem/Context:

How Verified:

**Comment by shalinijoshi19** [comment]
@paulcam206 is added to the review. #Closed

**Comment by shalinijoshi19** [comment]
@nesalang is added to the review. #Closed

**Comment by shalinijoshi19** [comment]
@matthidinger is added to the review. #Closed

**Comment by shalinijoshi19** [comment]
> 			this.renderedElement.style.marginLeft = "0";

Replace tabs with spaces pls! (@Paul, am hoping we are following that? )

---
Refers to: source/nodejs/adaptivecards/src/card-elements.ts:4384 in bec14bb. [](commit_id = bec14bb7f878148bf688ae87a05bd7d95dba4392, deletion_comment = False)

**Comment by shalinijoshi19** [comment]
>         // TODO: What's the right thing to do here?

Could you do me a favor and create an Issue for this TODO right here? in general should start tracking TODO's with issues

---
Refers to: source/nodejs/adaptivecards/src/card-elements.ts:4319 in bec14bb. [](commit_id = bec14bb7f878148bf688ae87a05bd7d95dba4392, deletion_comment = False)

**Comment by paulcam206** [comment]
> 			this.renderedElement.style.marginLeft = "0";

In other languages we have policies around whitespace. For certain we should be consistent within a single project. I'm hoping to have a CI check to validate formatting at some point in the future :)

---
In reply to: [477786464](https://github.com/Microsoft/AdaptiveCards/pull/2553#issuecomment-477786464) [](ancestors = 477786464)

---
Refers to: source/nodejs/adaptivecards/src/card-elements.ts:4384 in bec14bb. [](commit_id = bec14bb7f878148bf688ae87a05bd7d95dba4392, deletion_comment = False)

**Comment by shalinijoshi19** [comment]
Also any way we can push features up separately and into master as you dev them so they dont all get associated with a single PR or one set of multiple commits? just to containerize and serialize commits a bit more? Makes it easy to roll commits back should one be buggy.. it would help us track issues and completeness throughout the milestone leading up to release and not just the day of .. slightly easier to manage...thanks a ton..

**Comment by matthidinger** [comment]
@dclaux this branch seems good, do you have an ETA when you want to merge it? I just added my review

**Comment by shalinijoshi19** [comment]
Hmm seems to be a package-lock.json conflict that's likely blocking merge. @dclaux FYI

**Comment by dclaux** [comment]
No idea why the NodeJS build is failing. I made no change beside pulling master and it compiles just fine on my machine. I will override this and merge anyway if everyone agrees.

**Comment by paulcam206** [comment]
It should be rare indeed that we override a failing build -- especially when the build is failing for the thing you're authoring. We need to understand why the build failed before we can consider skipping it.

@matthidinger -- looks like some failing build stuff [here](https://microsoft.visualstudio.com/AdaptiveCards/_build/results?buildId=15249568). Do we need updates or refinements to our CI build definition?

**Comment by paulcam206** [comment]
Meanwhile, I'll trigger another build to see if it may be related to problems on the agent.

**Comment by paulcam206** [comment]
Looks like it was a hiccup with the CI job. We should try to understand why the build was flaky.

**Comment by dclaux** [comment]
It is also somewhat impractical IMO that changes only in the NodeJS path could be blocked being iOS checks (or the other way around.)  We should consider splitting things up.

**Comment by paulcam206** [comment]
I agree that it's impractical. Unfortunately, as far as I've been able to figure out, checks can be only be marked `required` at the branch level, not at the changed-directory level -- so we either live with people checking in build breaks, or we live with having unneeded checks running for all PRs.

**Comment by dclaux** [comment]
What's with the license/cla check that won't complete?

**Comment by dclaux** [comment]
Alright, and now another merge for a non-JS-related change has just reset the whole things. Happened twice today already. I am going to forcefully merge my changes now, after pulling the latest from master.

**Pull request merged**
