### PR TITLE
[Site] Fix keyboard accessibility for video modal

### PR DESCRIPTION
**Pull request by paulcam206**
## Related Issue
Fixes VSO 30862833

## Description
The "Watch Video" button on the main site wasn't behaving well to keyboard navigation. In particular, keyboard focus wasn't going to the video modal. I fixed that as well as the accessibility of the close button.

image
image

## How Verified
* local build, devtools

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/5255)

### CODE REVIEW

**Comment by RebeccaAnne** [comment]
I'm not sure this is working for me at the test site link. When I launch the video i don't see the focus, and after pressing tab once it seems to go to the "Android" link on the background page:

image

**Comment by paulcam206** [comment]
> I'm not sure this is working for me at the test site link. When I launch the video i don't see the focus, and after pressing tab once it seems to go to the "Android" link on the background page:
> 
> image

weird -- it sort of half-works for me... pressing `SPC` before `TAB` works, but `TAB` first is broken. I'll fix :)

**Comment by paulcam206** [comment]
I have a route to a fix, but I won't be able to finish 'til tomorrow :)

**Comment by paulcam206** [comment]
issue should be fixed -- had to trap the keyboard focus

**Comment by paulcam206** [comment]
@RebeccaAnne -- fyi, should be fixed now :)

**Review by RebeccaAnne — APPROVED** [review]

**Pull request merged**
