### PR TITLE
Jwoo/release1.2 debug symbol update

### LINKED ISSUE #3650: [iOS] AdaptiveCards published library should include symbol information
# Platform

* iOS

# Author or host
Teams

# Details
In order for crash dumps to be useful at all from our end we'd need to include symbols information in the packages, similar to what we did for UWP. Case in point crash reports like [these](https://rink.hockeyapp.net/manage/apps/334998/app_versions/941/crash_reasons/295575124).

### PR DESCRIPTION
**Pull request by nesalang**
## Related Issue
fixes #3650 

## Description
add debug symbols to binary produced.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/3651)

### CODE REVIEW

**Comment by shalinijoshi19** [comment]
@almedina-ms the .NET builds are failing with this error: Ideas?
\BA\5026\s\source\dotnet\Samples\AdaptiveCards.Sample.Html\AdaptiveCards.Sample.Html.csproj : error : NETSDK1056: Project is targeting runtime '-o' but did not resolve any runtime-specific packages. This runtime may not be supported by the target framework.
##[error]The build failed. Fix the build errors and run again.

SupportsInteractivity = true...
C:\BA\5026\s\source\dotnet\Samples\AdaptiveCards.Sample.Html\AdaptiveCards.Sample.Html.csproj : error : NETSDK1056: Project is targeting runtime '-i' but did not resolve any runtime-specific packages. This runtime may not be supported by the target framework.
##[error]The build failed. Fix the build errors and run again.

Windows notification config...
C:\BA\5026\s\source\dotnet\Samples\AdaptiveCards.Sample.Html\AdaptiveCards.Sample.Html.csproj : error : NETSDK1056: Project is targeting runtime '-o' but did not resolve any runtime-specific packages. This runtime may not be supported by the target framework.
##[error]The build failed. Fix the build errors and run again.

Timeline config...
C:\BA\5026\s\source\dotnet\Samples\AdaptiveCards.Sample.Html\AdaptiveCards.Sample.Html.csproj : error : NETSDK1056: Project is targeting runtime '-o' but did not resolve any runtime-specific packages. This runtime may not be supported by the target framework.
##[error]The build failed. Fix the build errors and run again.

**Comment by nesalang** [comment]
> @almedina-ms the .NET builds are failing with this error: Ideas?
> \BA\5026\s\source\dotnet\Samples\AdaptiveCards.Sample.Html\AdaptiveCards.Sample.Html.csproj : error : NETSDK1056: Project is targeting runtime '-o' but did not resolve any runtime-specific packages. This runtime may not be supported by the target framework.
> ##[error]The build failed. Fix the build errors and run again.
> 
> SupportsInteractivity = true...
> C:\BA\5026\s\source\dotnet\Samples\AdaptiveCards.Sample.Html\AdaptiveCards.Sample.Html.csproj : error : NETSDK1056: Project is targeting runtime '-i' but did not resolve any runtime-specific packages. This runtime may not be supported by the target framework.
> ##[error]The build failed. Fix the build errors and run again.
> 
> Windows notification config...
> C:\BA\5026\s\source\dotnet\Samples\AdaptiveCards.Sample.Html\AdaptiveCards.Sample.Html.csproj : error : NETSDK1056: Project is targeting runtime '-o' but did not resolve any runtime-specific packages. This runtime may not be supported by the target framework.
> ##[error]The build failed. Fix the build errors and run again.
> 
> Timeline config...
> C:\BA\5026\s\source\dotnet\Samples\AdaptiveCards.Sample.Html\AdaptiveCards.Sample.Html.csproj : error : NETSDK1056: Project is targeting runtime '-o' but did not resolve any runtime-specific packages. This runtime may not be supported by the target framework.
> ##[error]The build failed. Fix the build errors and run again.

@shalinijoshi19 the culprit was found. 
The error was from running RunAllTests.ps1.
 '-r' switch in the script caused .net command line tool to expect an argument that specifies a run time. but we use it as recursive option without argument since it's meant for our application. to fix added '--' to direct the switches and their arguments to the application.

**Pull request merged**
