### PR TITLE
Fix on issue AdaptiveOpenUrlAction Url property to Uri #954

### PR DESCRIPTION
**Pull request by mrbrennonwilliams**
@matthidinger 

Modified attributes and property to support Uri property type

### CODE REVIEW

**Comment by matthidinger** [comment]
@mrbrennonwilliams  this seems to be the FontSize change again. You might need to pull the latest origin/master and then commit/push your change to your forked master before submitting the PR

**Comment by mrbrennonwilliams** [comment]
So sorry about that. Was trying to do the PR from the github desktop app this time, and it really isnt clear to me when my local fork is synced with master. Clearly it isn't. Please bare with me ;-)

**Comment by mrbrennonwilliams** [comment]
@matthidinger 
I think this is now correct

**Comment by matthidinger** [comment]
This change was merged in with #973. Thanks Brennon

**Pull request closed without merging**
