### PR TITLE
.Net Template Internal Feed Changes

### LINKED ISSUE #3985: Build Package Feeds
- [x] Internal package feeds
- [x] Release package build pipeline

### PR DESCRIPTION
**Pull request by jwoo-msft**
## Related Issue
Fixes #3985 

## Description
1. Added internal nuget package feed support.
1. Added nuget.config for AEL MyGet source.
1. Updated Versioning mechanics for CI build

## How Verified
1. ran the unit tests for regression
2. tested nuget feed with wpf sample app

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/3986)

### CODE REVIEW

**Comment by paulcam206** [comment]
awesome -- glad you figured it out :)

**Comment by shalinijoshi19** [comment]
hey @nesalang, should this be  merged into @dclaux 's refactor branch ? If so then let's just do that ?

**Comment by jwoo-msft** [comment]
@shalinijoshi19, no we can't do that. if this is merged to the refactor branch, we can't build for .Net daily feed.

---
In reply to: [624837281](https://github.com/microsoft/AdaptiveCards/pull/3986#issuecomment-624837281) [](ancestors = 624837281)

**Comment by shalinijoshi19** [comment]
@jwoo-msft should this be updated to work with RC bits of AEL now instead of nightlies for stability?

**Comment by shalinijoshi19** [comment]
> @shalinijoshi19, no we can't do that. if this is merged to the refactor branch, we can't build for .Net daily feed.
> 
> In reply to: [624837281](https://github.com/microsoft/AdaptiveCards/pull/3986#issuecomment-624837281) [](ancestors = 624837281)

Could you help me understand why and also how are we tracking closure for this? Will this be merged directly into master? My worry is there are too many different topic branches for this same feature and we might miss something?

**Comment by jwoo-msft** [comment]
This is branch is going to be merged to man .NET branch. The main changes for this branch is at commit #5. I think the other changes shown here is due to rebasing to .NET main branch. I run the diff between two branches, and the diff was the same as in commit #5.

---
In reply to: [625773776](https://github.com/microsoft/AdaptiveCards/pull/3986#issuecomment-625773776) [](ancestors = 625773776)

**Comment by jwoo-msft** [comment]
yes, that's updated in .NET main branch.

thank you.

---
In reply to: [625773448](https://github.com/microsoft/AdaptiveCards/pull/3986#issuecomment-625773448) [](ancestors = 625773448)

**Pull request merged**
