### PR TITLE
Website: added label accessibility note to samples and schema explorer

### PR DESCRIPTION
**Pull request by matthidinger**
This work tracks an update to the website about our samples not using the latest accessibility features, such as Input Labels.

image

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/4807)

### CODE REVIEW

**Review by almedina-ms — APPROVED** [review]

**Comment by matthidinger** [comment]
@almedina-ms @golddove @RebeccaAnne can you guys take a look at this and let me know if it should supersede the issue tracking an update to all the card payloads? The verbiage is a little bit long and takes up a fair bit of space on the website but since it's temporary I feel like it's good enough, but let me know you thoguhts

**Review by golddove — APPROVED** [review]
Wording looks good to me

**Comment by RebeccaAnne** [comment]
Looks good to me too. I updated #4552 so that it no longer tracks warning banners, but still exists to track creating 1.3 aware versions of the cards to eventually replace the existing one.

**Review by RebeccaAnne — APPROVED** [review]
:shipit:

**Pull request merged**
