### PR TITLE
Adaptive Cards Studio - Alpha

### PR DESCRIPTION
**Pull request by DeeJayTC**
## Description
First alpha release as sources only for the new VSCode Extension

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/4337)

### CODE REVIEW

**Comment by shalinijoshi19** [comment]
@DeeJayTC could you share more details on what this extension is all about or add a reference to an issue or something where you might have already been discussing this ? Is this any relation to https://marketplace.visualstudio.com/items?itemName=tomlm.vscode-adaptivecards?

**Comment by DeeJayTC** [comment]
Hey @shalinijoshi19 sort of yes, its a completely new version of the VSCode Extension we introduced during the last community call. However just wait with merging, want to do a few more changes, publish it to market and have the really latest version checked in.

**Comment by DeeJayTC** [comment]
@shalinijoshi19 
[https://marketplace.visualstudio.com/items?itemName=madewithcardsio.adaptivecardsstudiobeta](https://marketplace.visualstudio.com/items?itemName=madewithcardsio.adaptivecardsstudiobeta)

**Comment by DeeJayTC** [comment]
@matthidinger  can you get anyone to merge this?

**Comment by shalinijoshi19** [comment]
@DeeJayTC we should be able to help out - @paulcam206 / @golddove another one from the community to help get merged in

**Pull request merged**
